### PR TITLE
Include both the veteran rank name and number in sentry message

### LINKED ISSUE #2369: Sentry messages should state the veteran rank name (not number) of the unit spotted
**Describe the bug**
battle messages display the veteran rank name of the units involved (e.g.  "disciplined Bowmen"), but sentry units display the veteran rank number ("v3 Bowmen"). 

**To Reproduce**
1. Sentry a unit
2. Have a veteran unit move within the sentry-trigger area.

**Expected behavior**
Sentry messages should display the veteran rank name.

**Screenshots**
image

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: e.g. 3.1-beta.1

### PR DESCRIPTION
**Pull request by XHawk87**
Fixes #2369

### CODE REVIEW

**Comment by blabber** [comment]
Always nice to see new contributors 🎉

Checks are pending, but I guess you didn't run clang-format on your changes. At least I am not used to seeing one parameter per line.

**Comment by XHawk87** [comment]
> Checks are pending, but I guess you didn't run `clang-format` on your changes. At least I am not used to seeing one parameter per line.
Nope, don't even know how to do that. C/C++ is not one of my languages. The way it was before was practically unreadable though, I couldn't easily tell which parameter related to which format symbol.

**Comment by hugomflavio** [comment]
Tested, working as expected
image

image

**Comment by hugomflavio** [comment]
@XHawk87 to run clang-format, first get it with
`apt install clang-format`

Then, the usual workflow is to run `git add [file]` for the files you wish to commit, then `git clang-format` (which will automatically target and rewrite the added files as needed), and `git add [file]` again if any file is changed by clang-format.

Since the commit has already been done, you'll need to manually run `clang-format -i [file]` (the -i flag tells clang to make the changes in the file itself). Then you can `git add [file]` and commit it.

**Comment by jwrober** [comment]
Also, best practice is to place new code into a branch and not `master` - https://longturn.readthedocs.io/en/latest/Contributing/pull-request.html

**Comment by XHawk87** [comment]
> Also, best practice is to place new code into a branch and not `master` - https://longturn.readthedocs.io/en/latest/Contributing/pull-request.html

It might be a good idea to link to this somewhere in a CONTRIBUTING file or the README. I looked through the project repo and github wiki and didn't see any references to these docs.

**Comment by lmoureaux** [comment]
> It might be a good idea to link to this somewhere in a CONTRIBUTING file or the README. I looked through the project repo and github wiki and didn't see any references to these docs.

Done, thanks for the suggestion!

**Comment by hugomflavio** [comment]
retested, working nicely.

image

merging.

**Pull request merged**
