### PR TITLE
Fix the chat widget

### LINKED ISSUE #739: Panels overlap by default
**Describe the bug**
The default layout of the panels doesn't do any work to prevent them from overlapping, and they do overlap.

**To Reproduce**
1. Start game
2. Reduce the window width to 1280px
3. Select a settler
4. See overlapping panels

**Expected behavior**

No overlap in autoplaced panels, ever.

**Screenshots**

Notice overlap between the settler and the chat area:
image

**Platform and version (please complete the following information):**
 - OS: any
 - Freeciv21 version: all so far

### LINKED ISSUE #1056: Chatline Widget cannot be resized
**Describe the bug**
The moveable chatline widget can't be make taller. There is no option to drag from the top or the bottom to make it taller to see more rows of data. You can make it wider by grabbing the right side, but not from the left.

**To Reproduce**
1. Attempt to drag the chatline widget from the top, notice you cannot
2. Attempt to drag the chatline widget from the bottom, notice you cannot
3. Attempt to drag the chatline widget from the left, notice you cannot

**Expected behavior**
The chatline is to be moveable around the screen/window and minimized when wanted.
A player should be able to resize the widget from all 4 directions as they see fit.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: All
 - Freeciv21 version: `master` at https://github.com/longturn/freeciv21/commit/7a9a40ca3d14750d325fed25282fadf76f4147b1
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

### LINKED ISSUE #1074: Chat window disappears when minimising
**Describe the bug**
If the chat is partially below the screen and you hit collapse, the "restore" button technically goes outside the screen and makes it impossible to restore.

**To Reproduce**
1. Move chat widget such that it is partially below the screen
2. Hit minimize
3. No way to restore.

**Expected behavior**
Some way to restore the chat. Maybe give chat a button in top row just like messages. 

**Platform and version (please complete the following information):**
master

**Additional context**
Maybe minimize the chat such that it rolls upwards and the minimize button stays in the same place rather than roll downwards such that the chatbox stays in the same place.

### LINKED ISSUE #1143: Corner is disconnected from mouse when resizing chat window
**Describe the bug**
Described by @lmoureaux in #1081. 

**To Reproduce**
    Grab the bottom left corner of the chat window
    Move the mouse up until above the top of the chat window. The chat window hits its minimum height, which is fine.
    Move the mouse down again. The chat window expands, but the corner is "disconnected" from the mouse.

**Expected behavior**
Corner always stays with the mouse

**Platform and version (please complete the following information):**
- master + #1081

### LINKED ISSUE #1144: It is possible to move chat window out of the screen
**Describe the bug**
Reported by @lmoureaux in #1081.  it's possible to move the chat window out of the screen if the main window is smaller than the screen. 

**To Reproduce**
  - Grab the left side, move it to the left (out of the window area)
  - Grab the right side, move it to the left (also out of the window area)

**Expected behavior**
prevent moving any edge out of the ~screen~ window.

**Platform and version (please complete the following information):**
- master + #1081

### LINKED ISSUE #1145: Use Qt::Edges instead of a custom enum for resizing widgets
**Describe the bug**
No bug, but codacy complains about  [MISRA 16.2 ](https://lost-contact.mit.edu/afs/pdc.kth.se/roots/ilse/v0/pdc/vol/matlab/r2016b/help/codeprover/ref/misrac2012rule16.2.html)whenever Qt enums are used. 

**To Reproduce**
Look at #1081 

**Expected behavior**
No problems with codacy ?

**Platform and version (please complete the following information):**
- master

**Additional Context**
Do nothing. Maybe codacy is a false positive.

### LINKED ISSUE #1158: Chat line widget's location not saved
**Describe the bug**
If you move the server log/chat line widget to a location of your choosing (e.g. lower left corner) and save client settings, the setting is not saved and the next time you come into a game the widget is moved back to the upper right near the messages widget.

**To Reproduce**
1. Open a game (any kind)
2. Resize and move the server lot/chat widget to a spot of your choosing
3. Save settings
4. Exit the game
5. Come back into the game
6. See issue - the chat widget will be back to the upper right

**Expected behavior**
The client should accept and remember my new location and widget geometry.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux (but assume its an issue on other OS)
 - Freeciv21 version: 3.0-beta3]
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

### LINKED ISSUE #1159: Messages widget is "below" Chat widget
**Describe the bug**
If the moveable chat widget is moved to the upper right corner and the messages widget is shown, the chat is on top of it and hides messages.

**To Reproduce**
1. Open a game (any game)
2. Hide messages widget
3. Move chat widget to upper right corner
4. Show messages
5. See error

**Expected behavior**
Messages should be on top

**Screenshots**
image

**Platform and version (please complete the following information):**
 - OS: Linux (assume its there on other OS)
 - Freeciv21 version: 3.0-beta3
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

### PR DESCRIPTION
**Pull request by lmoureaux**
Had some "fun" reviewing the chat widget code and fixing most open issues. See commit messages for details.

Closes #1056.
Closes #1074.
Closes #1145.
Closes #1144.
Closes #1143.
Closes #1159.
Closes #1158.
Closes #739.

### CODE REVIEW

**Review by jwrober — CHANGES_REQUESTED** [review]
* 1074 is resolved
* 1145 is resolved - really enhances the ease of resizing both chat and messages!
* 1144 is resolved
* 1143 is resolved - however it is really hard to grab the upper right corner with the minimize button the way it is right now. Maybe move the minimize button to the left a little bit?
* 1159 is resolved - chat now is below messages and above the minimap
* 1158 is partially resolved. If you move the chat widget to a spot on the screen it does stay there while in the game, however the location is not saved so the location is not the same when you come out and come back in to a game. I think it should stay where I put it until I put it in another spot.
* 739 is resolved

One other issue I noticed is you can grab the title bar of the messages box and drag it down. I think it needs to be pinned to the top bar. The new Qt::Edge deal is great otherwise.

**Comment by lmoureaux** [comment]
> If you move the chat widget to a spot on the screen it does stay there while in the game, however the location is not saved so the location is not the same when you come out and come back in to a game. I think it should stay where I put it until I put it in another spot.

Works for me

**Comment by lmoureaux** [comment]
> it is really hard to grab the upper right corner with the minimize button the way it is right now

The resize arrow cursor is now only shown when resizing would work

> you can grab the title bar of the messages box and drag it down

My bad, fixed

**Review by jwrober — APPROVED** [review]

**Comment by lmoureaux** [comment]
>  If you move the chat widget to a spot on the screen it does stay there while in the game, however the location is not saved so the location is not the same when you come out and come back in to a game. I think it should stay where I put it until I put it in another spot.

New commit addressing this after our discussion and reproducing it on my side.

**Pull request merged**
