### PR TITLE
City dialog: push to the sides

### LINKED ISSUE #728: Change the City Dialog layout so it looks more centered
**Is your feature request related to a problem? Please describe.**
As stated in the issue title, change the way the city dialog is shown on the screen. Right now there is an artificial spacer in place between the city worked tiles and the two side panels and when shown on the screen makes it look like the whole thing is off center.

**Describe the solution you'd like**
Instead of an artificial spacer, determine the size of the city center is in pixels and then tuck the two side panels to the left and right side. Then as zoom in/out happens, the side panels are always right next to the city center. The city center is already centered on the screen, so this is more of a movement of the side panels, mainly the left one.

**Describe alternatives you've considered**
Doing nothing is also an option. This request is more about making the client look polished and professional.

**Additional context**
None, but here are a couple screen shots showing the space on the left side due to the artificial spacer.

image

image

### LINKED ISSUE #1714: Suggestions for new city dialog left "side" bar
Master branch is working to develop a new city dialog. Some comments on the side bar as it stands as of https://github.com/longturn/freeciv21/commit/b688f424a69b55abcafdeeab6997e1464df3a10a.

1. IMO, the dialog should be closer to the Map View button. Even better if it "unfolds" from the top menu in that area when invoked

image

2. As shown in the image above, if there are no supported improvements or units, nothing is shown but the scroll bar. Suggest that the bar is always the same size like this:

image

and when "blank" has text that says something like "no supported improvements" or "no supported units". Might also be good if we can add a separator in there to add a visual differentiation between improvements, wonders and units.

3. Lastly, I think the city icon and the supported items bar should be coupled together with no separation between them.

### PR DESCRIPTION
**Pull request by lmoureaux**
This is one step further towards #1591. It pushes the panels to the side and addresses #1714.

Closes #728.
Closes #1714.

### CODE REVIEW

**Review by jwrober — CHANGES_REQUESTED** [review]
This is a good start. I have some suggestions.

**Comment by jwrober** [comment]
Suggestions:

- Consolidate all the tabs into one bank on the left. General / Production / Citizens / Governor.
- Move the city Next/Previous/Close button to above the city name
- Have a look at the sprites that go along with the varying values in the screen shot below. They don't update properly if you switch between themes.

image

**Comment by lmoureaux** [comment]
> * Consolidate all the tabs into one bank on the left. General / Production / Citizens / Governor.

This would make it harder to develop the new layout, so I'm not doing this.

> * Move the city Next/Previous/Close button to above the city name

Done along with a second pass on the rest of the layout.

> * Have a look at the sprites that go along with the varying values in the screen shot below. They don't update properly if you switch between themes.

Opened #1803 about this.

**Review by jwrober — APPROVED** [review]
Second commit is much better.

**Pull request merged**
