### PR TITLE
Iconv

### PR DESCRIPTION
**Pull request by mir3x**
Not sure if everythign works bc conversions are from UTF8 -> UTF8, maybe we could add language switcher in client

### CODE REVIEW

**Comment by lmoureaux** [comment]
Worth mentioning that `QTextCodec` [will be deprecated in Qt6](https://bugreports.qt.io/browse/QTBUG-75665), so it's not like we're 100% done with text encoding issues :cry: .

We could remove transliteration support as well, it's always `false` for the Qt client.

**Comment by mir3x** [comment]
Seems they changed their mind:
https://doc-snapshots.qt.io/qt6-dev/internationalization.html
find_package(Qt6 COMPONENTS Core5Compat REQUIRED)
target_link_libraries(mytarget PUBLIC Qt6::Core5Compat)

**Comment by lmoureaux** [comment]
> Seems they changed their mind:
> https://doc-snapshots.qt.io/qt6-dev/internationalization.html
> find_package(Qt6 COMPONENTS Core5Compat REQUIRED)
> target_link_libraries(mytarget PUBLIC Qt6::Core5Compat)
> 
> That new QStringEncoder/Decoder looks eazy anyway.

The `xxCompat` is only provided for the first releases and will disappear after that. Was just pointing out that sadly another rewrite will be needed.

**Comment by mir3x** [comment]
Hmm, some bugs in japanese in russian are not related to that patch or patches from few days back

**Pull request merged**
