### PR TITLE
Remove data/misc/cityicon.png

### LINKED ISSUE #985: Drop the old city dialog icon
**Is your feature request related to a problem? Please describe.**

We have an icon for the city dialog, located at `data/misc/cityicon.png`. It is no longer in use.

**Describe the solution you'd like**

Delete it.

**Describe alternatives you've considered**

Keep it in case we want to make the city screen windowed again. We'd probably not use it anyway.

**Additional context**

#978 #984

### PR DESCRIPTION
**Pull request by jwrober**
Closes #985

### CODE REVIEW

**Comment by lmoureaux** [comment]
When I wrote "no longer used", it may have been an overstatement. I see that it's still referenced from `misc/icons.spec`. `tileset.cpp` has an enumerator named `ICON_CITYDLG` that I bet must still load it.

**Comment by jwrober** [comment]
> When I wrote "no longer used", it may have been an overstatement. I see that it's still referenced from `misc/icons.spec`. `tileset.cpp` has an enumerator named `ICON_CITYDLG` that I bet must still load it.

Ok so maybe leave the file alone? I'm not going to touch the code.

**Comment by lmoureaux** [comment]
> Ok so maybe leave the file alone? I'm not going to touch the code.

I'm trying to push you into it :joy: I can do the coding part, I'll push to your branch (assuming you kept the "allow edits by maintainers" box checked)

**Comment by jwrober** [comment]
I'll look at the `misc/icons.spec` and you can do the `tileset.cpp` fix

**Comment by lmoureaux** [comment]
Did the C++ changes and rebased on top of `master` so the actions can succeed.

**Pull request merged**
