### PR TITLE
Add AUR to README

### PR DESCRIPTION
**Pull request by psampathkumar**

### CODE REVIEW

**Review by lmoureaux — COMMENTED** [review]
Should we add a section next to Nix and FreeBSD?

Is there a way to make the label as tall as the other two?
image

**Comment by psampathkumar** [comment]
I tried, but no. 

Regarding nix and bsd, i considered that, but i think its better to just give a badge and not repeat instructions which are already on arch wiki.

**Comment by jwrober** [comment]
What about horizontal centering of the image/badge with the other two? Maybe put all of them into an html table?

**Comment by blabber** [comment]
Too bad that AUR and FreeBSD use incompatible versioning schemes (the FreeBSD framework cannot handle the scheme that Freeciv uses). Otherwise you could also use a Repology badge:

https://repology.org/project/freeciv21/badges

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
