### PR TITLE
Miscelanous useless files/functions/options

### PR DESCRIPTION
**Pull request by mir3x**
Shaved 2k lines

### CODE REVIEW

**Comment by mir3x** [comment]
need to check something

**Comment by lmoureaux** [comment]
What happens when it loads an old config file with removed Gtk options?

**Comment by mir3x** [comment]
>> What happens when it loads an old config file with removed Gtk options?
I tested, I didnt saw any rogue backtraces :D or logs.

**Comment by mir3x** [comment]
those old gtk options are not saved again to new options after reading old 2.6 format.

**Comment by lmoureaux** [comment]
Whoops Travis failed

**Pull request merged**
