### PR TITLE
Monster refactor of shortcut management

### LINKED ISSUE #1088: When the messages widget is focused, zooming in the map doesn't work (but only with the default `+` key)
**Describe the bug**
When you focus the messages widget by clicking inside it, zooming in doesn't work, but zooming out and reseting zoom both work.

**To Reproduce**
1. Open the messages widget
2. Click inside it
3. Click `-` to zoom out (works)
4. Click `+` to zoom in (doesn't work)
5. Click `Ctrl + Backspace` to reset zoom (works)

**Expected behavior**
It should either all work or all not work

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
It's nothing to do with which `+` and `-` you use for zooming, both numpad and non-numpad work the same.

Probably has something to do with the `+` button itself, if one rebinds the "Zoom in" key to anything else it works just fine

### LINKED ISSUE #1090: Assigning keyboard shortcuts doesn't completely remove the previous ones
**Describe the bug**
If you manually change a keyboard shortcut (changing it from the default), then change it again, then change it back, it doesn't work. The client just says "already assigned to \<function\>", even though it's the same function it's being assigned to. As if it remembers past shortcuts somehow.

**To Reproduce**
1. Open shortcuts settings, assign `numpad /` to "zoom in", click "Ok"
2. Open shortcuts settings, assign `numpad +` to "zoom in", click "Ok"
3. Open shortcuts settings, assign `numpad /` to "zoom in", click "Ok"
4. Observe an error message `Num+/ is already assigned to Zoom in`

**Expected behavior**
It shouldn't remember shortcut history and should completely replace the old keyboard shortcut

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

### PR DESCRIPTION
**Pull request by lmoureaux**
Closes #1090 and more bugs I spotted while going through the code.
Closes #1088

See some detailed explanations in commit messages.

**Things to test:**
* Check that the defaults make sense
* Try all shortcuts, make sure they do something
* Change shortcuts and repeat the above, including assigning a mouse button to keyboard-like shortcuts (e.g. Reload Tileset) and a key sequence to mouse-like shortcuts (e.g. Scroll Map)
* Do it with different themes
* Check that the shortcuts are restored correctly on restart

Assigning two reviewers so you can split the work if you like...

*Note: the on-disk format of shortcuts has changed and there's no backward compatibility code*

### CODE REVIEW

**Comment by lmoureaux** [comment]
The clang failure is https://github.com/llvm/llvm-project/issues/48582, I wonder how it succeeds at all on Linux.

**Comment by lmoureaux** [comment]
Closes #1088

**Review by jwrober — APPROVED** [review]
seems to work for me. I changed a ton of the options and they stayed put after a restart of the client. I was able to test majority of them. Only one I couldn't was to explode a nuke. The only default I would change is the city output to Crtl-O instead of W

**Comment by lmoureaux** [comment]
> seems to work for me. I changed a ton of the options and they stayed put after a restart of the client. I was able to test majority of them. Only one I couldn't was to explode a nuke. The only default I would change is the city output to Crtl-O instead of W

Thanks! Ctrl+W is the shortcut inherited from the Gtk client, but we can indeed revise that some day.

**Comment by pranavtifr** [comment]
I guess this is ready for merging. We can merge as soon as the commented out code is deleted.

**Comment by lmoureaux** [comment]
> I guess this is ready for merging. We can merge as soon as the commented out code is deleted.

Which commented code?

**Pull request merged**
