### PR TITLE
Make "Advanced unit selection" dialog movable

### LINKED ISSUE #1111: Make "Advanced unit selection" dialog movable
**Describe the bug**
Currently it's always-on-top, centered, and not movable. This makes it hard to look at the map while choosing the various options for unit selection.

**To Reproduce**
1. Open the "Advanced unit selection" dialog
2. Observe a center part of the map now blocked by the dialog with no way to move it around

**Expected behavior**
I'd expect it to have a proper title bar to make it movable (also with a close button like other dialogs have)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

### PR DESCRIPTION
**Pull request by Koffy25**
Closes #1111

### CODE REVIEW

**Comment by lmoureaux** [comment]
Will test later tonight/tomorrow, for now I noticed that the commit message looks strange, maybe you want to change it?

**Comment by Koffy25** [comment]
> Will test later tonight/tomorrow, for now I noticed that the commit message looks strange, maybe you want to change it?

Done.

**Comment by Koffy25** [comment]
I got an email that says the windows clang step failed but it says passed in the pull request so I'll assume all is well.

**Comment by lmoureaux** [comment]
> I got an email that says the windows clang step failed but it says passed in the pull request so I'll assume all is well.

Indeed, I saw it too. Probably an earlier version of the commit, the Windows clang build isn't 100% reliable because of frequent network errors when pulling dependencies.

**Comment by jwrober** [comment]
I don't think its appropriate for me to speak to code quality, however I did test this PR in my local and it does as advertised. The dialog is no longer modal and does allow me to move it around. It may also be a model for us to get rid of the hacked dialogs.

**Review by lmoureaux — COMMENTED** [review]
Since it was confirmed that this works, my only question is why `disband_box` was also moved?

**Comment by Koffy25** [comment]
> Since it was confirmed that this works, my only question is why `disband_box` was also moved?

At one time it was getting the "unexpected class name" error but the recursive include issue is fixed now so I'll move it back

**Comment by lmoureaux** [comment]
Thanks!

**Pull request merged**
