### PR TITLE
Optimize governors

### PR DESCRIPTION
**Pull request by lmoureaux**
Profiling has shown a few low hanging fruits to speed up governors. This implements them.

### CODE REVIEW

**Comment by hugomflavio** [comment]
Time from entering password to a responsive client decreased from ~1m30s using the master to ~35s using this PR.

**Comment by jwrober** [comment]
Code Factor not happy. Correction needed?

**Comment by lmoureaux** [comment]
It's unhappy because I modified a complex function without simplifying it.

**Comment by jwrober** [comment]
Ok Sounds good.

**Review by jwrober — APPROVED** [review]
Seems to improve performance for me.

**Pull request merged**
