### PR TITLE
Remove civstatus

### LINKED ISSUE #1271: Get rid of extraneous gold and science widget
**Is your feature request related to a problem? Please describe.**
We have a widget right now that shows the gold output as well as the bulbs output. Here is a sample

image

**Describe the solution you'd like**
We don't need it and it causes clutter. The top bar shows the same thing.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by lmoureaux**
The civstatus widget was introduced as a first-gen top bar, but never reached
maturity and is now superseded. Remove it.

Closes #1271.

### CODE REVIEW

**Comment by lmoureaux** [comment]
May need an update of the main client screenshot.

**Review by jwrober — APPROVED** [review]

**Comment by jwrober** [comment]
@lmoureaux - looks like I found the issue with `patch`, there is a conflict that needs resolved first.

**Comment by jwrober** [comment]
I was able to manually delete the files that the patch was trying to do. With that, the widget does go away and am able to compile with no issue.

**Comment by lmoureaux** [comment]
Conflict fixed

**Pull request merged**
