### PR TITLE
Bring docs up to date with some gui changes

### PR DESCRIPTION
**Pull request by jwrober**
No related issue.

### CODE REVIEW

**Review by lmoureaux — COMMENTED** [review]
Are the window decorations on the new screenshot there to make the Flatpak team happy? If so, the screenshot should also include the window shadow and be significantly smaller so it gets displayed at 1:1 on their website.

**Comment by jwrober** [comment]
I made this change before I was aware of the flathub business. I made it to make me happy, not them :)

**Comment by lmoureaux** [comment]
I think it would make sense to make the screenshot smaller, I can't even display it at 1:1 on my screen. Let's take the Flathub dimensions as a guideline?

**Comment by jwrober** [comment]
I'm fine to make the image smaller. I don't like the dropshadow requirement tho.

**Comment by lmoureaux** [comment]
> I'm fine to make the image smaller. I don't like the dropshadow requirement tho.

Make it smaller without window decorations and if they're unhappy, explain that there is a conflict in their guidelines between "default configuration" (which is fullscreen) and "drop shadows". Since shadows are cosmetic, we choose to follow the configuration guideline.

**Comment by jwrober** [comment]
I'll retake the screen shot in full screen mode and resize following their guidelines on size and push another commit.

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
