### PR TITLE
Add guidelines for math usage in the documenation

### LINKED ISSUE #1719: Document the usage of latex math
**What should be documented? Is there something wrong in the documentation?**
Freeciv21 is math heavy and our documentation has a lot of mathematical formulas in it to help players understand how varying elements of the game are calculated. RTD allows us to use latex formatting for the `:math:` directive, however it is a bit of alchemy to a regular documentation writer unless you have used latex before.

**Do you have suggestions?**
In the contributing section, could have a page that explains how to format math formulas using the latex feature of the `:math:` directive.

### PR DESCRIPTION
**Pull request by lmoureaux**
Keep the topic short because math should be used sparingly. In particular, a full Latex reference is out of scope here; Latex is widespread enough that there are countless resources on the topic. The syntax is also way to complex to explain in a single page.

Closes #1719.

### CODE REVIEW

**Comment by jwrober** [comment]
That was fast :)

**Review by jwrober — APPROVED** [review]
I think this is good. My only comment would be to aid the reader with a link to a "good source" to help those that might be overwhelmed with all the LaTeX documentation to know which one to use.

I do like the "use sparingly" comment. Maybe more emphasis on usage in  the coding section is appropriate, while in manuals is probably not appropriate as an example?

**Comment by lmoureaux** [comment]
> My only comment would be to aid the reader with a link to a "good source" to help those that might be overwhelmed with all the LaTeX documentation to know which one to use.

Added a Wikibooks I learned a lot from, it's however more a reference than a tutorial.

> Maybe more emphasis on usage in the coding section is appropriate, while in manuals is probably not appropriate as an example?

Given how often we get questions about the price of unit upgrades, I think we shouldn't push back too hard on  math in "normal" docs.

**Comment by jwrober** [comment]
> Given how often we get questions about the price of unit upgrades, I think we shouldn't push back too hard on math in "normal" docs.

Simple formulas I think are fine anywhere. It's the super complex ones that we have in the coding area that I think need to stay there. "Normal" docs should be readable by anyone with Algebra I level math knowledge (e.g. what every US high school teaches).

**Comment by lmoureaux** [comment]
Wording suggestion?

**Comment by jwrober** [comment]
When math formulas are used on non-technical pages (such as any one of the manuals), the reasoning should be relatively simple following elementary algebra [https://en.wikipedia.org/wiki/Elementary_algebra]

**Pull request merged**
