### PR TITLE
Packaged for Nix/ NixOS

### PR DESCRIPTION
**Pull request by dmadisetti**
Packaged for the Nix package manager (which is usable on Mac / NixOS/ general linux)

### CODE REVIEW

**Comment by lmoureaux** [comment]
Thank you for the contribution! I'm glad you could figure out the `-DFREECIV_DOWNLOAD_FONTS=0` :+1:
I have a few questions, please forgive my ignorance about Nix (looks like it's packaged for Ubuntu/Debian, I'll give it a try):
* How can we test this to make sure we don't introduce regressions? Maybe upstream provides a Github action we can use?
* You mentioned MacOS. Do you know if Nix can be used to create dmgs? We're currently using vcpkg and it's both very slow and quite unstable

**Comment by dmadisetti** [comment]
Yes! We can use: github.com/cachix/install-nix-action. Tests can be added to the derivation as well to ensure valid builds too.

Hmm, I don't know enough about dmgs to really comment. But Nix is developed specifically to address instability

**Comment by dmadisetti** [comment]
Not sure if it'll run for MacOS. It should? I have no way of testing beyond a quick cross compilation check. I guess the CI will tell. The only dependency I couldn't resolve was Qt5's Karchive, but that's already present on MacOS? Wasn't clear on that.  I only looked at x86 as well, but that could potentially be expanded.

I can add a snippet to https://github.com/longturn/freeciv21/blob/master/docs/Getting/compile.rst as well. Once this is merged, nix users can just do `nix run github:longturn/freeciv21#` .

**Comment by dmadisetti** [comment]
@lmoureaux Can you run the CI?

**Comment by lmoureaux** [comment]
Thanks for the updates, I had missed them since this was a busy week. I'll look more over the week-end.

**Comment by dmadisetti** [comment]
No problem, thanks. 

How is KF5Archive dependency resolved on macos? I don't see any explicit call in the other workflows and nix doesn't package it for mac

**Comment by lmoureaux** [comment]
It's resolved through vcpkg, which has an automatic way of discovering dependencies from CMake. It compiles it from source

**Comment by lmoureaux** [comment]
I suggest we leave MacOS out and merge this. Let's also make it a weekly build so we don't use compute needlessly but still check for regressions (like `windows_clang_msvc`).

**Comment by jwrober** [comment]
Would appreciate if we put the `flake.nix` in the `dist` directory. This is where we store flatpak and snapcraft yaml files. Docs updates are always encouraged.

**Comment by jwrober** [comment]
appreciate the submission @dmadisetti

**Comment by lmoureaux** [comment]
I can't edit the branch in this PR -> superseded by #1934

**Pull request closed without merging**
