### PR TITLE
Update CMake files to use FindPython3

### PR DESCRIPTION
**Pull request by lmoureaux**
FindPythonInterp is deprectaed. FindPython3 is a drop-in replacement.

### CODE REVIEW

**Comment by lmoureaux** [comment]
Looks like I broke Windows. Apple failed for a different reason

**Comment by jwrober** [comment]
I am going to run this on Windows clang to double check its ok there.

**Comment by lmoureaux** [comment]
Let me tune a few knobs so we can trigger this on Github

**Comment by lmoureaux** [comment]
> Let me tune a few knobs so we can trigger this on Github

Full build starting here: https://github.com/lmoureaux/freeciv21/actions/runs/7012070710

**Comment by lmoureaux** [comment]
> Full build starting here: https://github.com/lmoureaux/freeciv21/actions/runs/7012070710

Succeeded (except for macOS with the usual bug)

**Review by jwrober — APPROVED** [review]
Windows Clang worked for me too on my local.

**Pull request merged**
