### PR TITLE
Add a player's national flag on the map view button on the top bar

### LINKED ISSUE #1205: Add Nation's Flag to the Map View Icon in Top Bar
**Is your feature request related to a problem? Please describe.**
Right now, the icon on the far left in the top bar - what I am calling the Map View icon - shows the year and the turn. If you hover your mouse over the button, then you can see some more information about your nation in a pop up widget.

**Describe the solution you'd like**
I would like to see the nation's flag added to this icon/button. Preferably farthest left and then the text showing the year and turn number to the right of the flag.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1205 

image

### CODE REVIEW

**Review by lmoureaux — CHANGES_REQUESTED** [review]
The flag remains present for global observers, which shouldn't be the case:

image

**Comment by jwrober** [comment]
Oh good catch. Thoughts on what should put in place? I could go find a generic globe svg or something or just leave the space blank. Kind of like the globe icon as a visual indicator.

**Comment by lmoureaux** [comment]
The globe sounds good. Can make an svg if you need, it's easy.

Oh and also remove these, they don't do anything:
```cpp
    sw_map->setIcon(QIcon());
```

**Comment by jwrober** [comment]
> 
> Oh and also remove these, they don't do anything:
> 
> ```c++
>     sw_map->setIcon(QIcon());
> ```
Per Qt it clears it and I needed it from when you leave a game and join another without quitting.

**Comment by lmoureaux** [comment]
> > Oh and also remove these, they don't do anything:
> > ```c++
> >     sw_map->setIcon(QIcon());
> > ```
> 
> Per Qt it clears it and I needed it from when you leave a game and join another without quitting.

Well yes, they do change the icon to an empty icon, but since you're changing it again immediately afterwards it's weird that it matters.

**Comment by jwrober** [comment]
I found the "solution" on a Qt forum. Without those lines the icon is not updated to a new value. Don't 100% understand why it is, but it is.

**Review by lmoureaux — APPROVED** [review]

**Comment by lmoureaux** [comment]
Needs a rebase

**Pull request merged**
