### PR TITLE
Fix hover over actions on unit controls bar (unit_action)

### LINKED ISSUE #1866: Hovering over a unit command on the controls bar shows a gray box
**Describe the bug**
If you hover your mouse over a unit action icon on the unit controls bar, the icon shows as a grey box.

**To Reproduce**
1. Open a game
2. Select a unit
3. Hover mouse over an action icon in the unit controls bar at the bottom of the screen.

**Expected behavior**
You should get a visual highlight of some kind, not a complete opaque block.

**Screenshots**
image

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-dev (seems to work fine in 3.0.rc-3)
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1866

### CODE REVIEW

**Comment by lmoureaux** [comment]
Code looks fine. What does it look like?

**Comment by jwrober** [comment]
image

**Comment by daavko** [comment]
This PR would also benefit from a small change here: https://github.com/longturn/freeciv21/blob/master/client/hudwidget.cpp#L828
, swapping the icon painting and the focus box painting, so the icon is drawn _on top_ of the focus box, not behind it. If you look closely the icon in a focused button is grey instead of white

**Comment by jwrober** [comment]
I see the code, but not sure what I would need to do.

**Comment by daavko** [comment]
Move the `icon.paint()` call just after the end of the `if` block. That should be enough.

**Comment by jwrober** [comment]
Ok that change seems to help
image

**Review by daavko — APPROVED** [review]
I approve of this PR

**Pull request merged**
