### PR TITLE
Switch to requiring Qt 5.15

### LINKED ISSUE #1073: Rename deprecated QString::SkipEmptyParts to Qt:: SkipEmptyParts
**Describe the bug**
Deprecation warning in recent versions of Qt

**To Reproduce**
1. Compile
2. See warning

**Expected behavior**
No warning

**Platform and version (please complete the following information):**
master

**Additional context**
We need to wait until we get required Qt release in Ubuntu LTS

### PR DESCRIPTION
**Pull request by lmoureaux**
This PR implements the Qt 5.15 requirement in CMake, updates the documentation accordingly, removes all deprecated constructs, and asks Qt to disable them. The CI is also updated to use Ubuntu 22.04.

See #1198.
Closes #1073.
See also #608, #849.

### CODE REVIEW

**Comment by lmoureaux** [comment]
`clang-tidy-review` fails because it uses the workflow file from `master`, which still uses Ubuntu 20.04.

**Comment by jwrober** [comment]
We had previously discussed on Discord that we would not do any Qt stuff until we pushed a stable release. I think this might be premature.

**Comment by jwrober** [comment]
I think we can do this one after the Beta.6 release.

**Comment by lmoureaux** [comment]
Rebased.

**Review by jwrober — APPROVED** [review]
Works for me. Just need to get the CI to cooperate.

**Pull request merged**
