### PR TITLE
Use compile_commands.json with clang-tidy

### PR DESCRIPTION
**Pull request by lmoureaux**
Otherwise it can't find headers. Also reduce the number of steps using features
of clang-tidy-review.

Hopefully this works...

### CODE REVIEW

**Comment by pranavtifr** [comment]
Set base dir is probably not needed. I added that to try and use the artifacts from Ubuntu build..but doesn't work that way.

**Comment by lmoureaux** [comment]
Yeah I removed it, but I added `build_dir` to match what we do elsewhere. I'm not even sure if we support in-source builds :sweat_smile:

**Comment by pranavtifr** [comment]
Uh oh. You broke it 😛
And i meant 
```
      - name: Set base_dir
        run: echo "base_dir=$(pwd)" >> $GITHUB_ENV
```
These aren't needed either.

**Comment by pranavtifr** [comment]
A nice improvement would be if we can cache clang-tools. Then this would a fast check!

**Comment by pranavtifr** [comment]
Can you bump version to 0.9.0 ? I think that fixes it.

**Comment by pranavtifr** [comment]
Still fails :/

**Comment by lmoureaux** [comment]
```
clang-tidy failed with return code 1 and error:
Error while trying to load a compilation database:
Could not auto-detect compilation database from directory "build"
No compilation database found in /github/workspace/build or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
```

**Comment by pranavtifr** [comment]
Ya, I'm just looking at the integration bug. Clang-tidy seems to work ok in my PR. (I did that so that we can have some extra cpp changes to check with), 
The integration bug wasnt there yesterday :/

**Comment by lmoureaux** [comment]
Let's merge this so we get a green check mark at least?

**Pull request merged**
