### PR TITLE
Fix popup when disembarking 

### LINKED ISSUE #439: Unit disembark off ship not able to with mouse, only keyboard
I have a unit that is loaded on a ship. I activate the unit, press 'g' and then click the tile I want the unit to go to. In below screen shot I am clicking on the tile to the right of the Explorer in Trireme (shield) and nothing happens.

image

If I use the right arrow on the keypad, I get the menu of what to do, which is what I would expect with the mouse click.

image

### PR DESCRIPTION
**Pull request by mir3x**
Seems out of place, might introduce some tranport bugs, didnt observed any so far

### CODE REVIEW

**Comment by lmoureaux** [comment]
I want to test this before merging. Or maybe @jwrober ?

Closes #439

**Comment by jwrober** [comment]
I would like the opportunity to test this. Let me merge the diff to my local repo and test a new compile.

**Comment by jwrober** [comment]
Ok I was able to place some units out of a transport exactly where I wanted them I think this fixes the issue.

**Comment by lmoureaux** [comment]
Thanks for the check!

**Pull request merged**
