### PR TITLE
Add a genetic lab sprite

### LINKED ISSUE #1952: Need a genetics lab sprite
**Is your feature request related to a problem? Please describe.**
While working on pyciv, found that we don't have a sprite for the genetics lab improvement

**Describe the solution you'd like**
Either find an existing one or ask one to be created.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1952

### CODE REVIEW

**Review by lmoureaux — CHANGES_REQUESTED** [review]
Need SPDX information for the small sprite too

**Comment by jwrober** [comment]
> Need SPDX information for the small sprite too

We do not have `.license` files for any of the other `-small` variants.

**Comment by lmoureaux** [comment]
We should eventually if we want to implement #809

**Comment by jwrober** [comment]
Let's do the SPDX for `-small` files in a separate PR to get all of them at once.

**Review by lmoureaux — APPROVED** [review]
Makes sense, hopefully we don't forget what we know now...

**Pull request merged**
