### PR TITLE
Add an arm64 cross compilation to the CI

### LINKED ISSUE #1973: .deb package based on ARM silicon
**Is your feature request related to a problem? Please describe.**
We have some folks using ARM based Chromebooks, so we should support them with a native binary.

**Describe the solution you'd like**
Create another `.deb` package, but using a ARM based VM on the CI.

**Describe alternatives you've considered**
None

**Additional context**
Came up on Discord -- https://discord.com/channels/378908274113904641/402213035865014272/1115468803632025683

### PR DESCRIPTION
**Pull request by lmoureaux**
Chromebooks use arm64 so there is some demand to provide packages for this architecture.

Closes #1973.

### CODE REVIEW

**Comment by jwrober** [comment]
Is this ready for review or does it need more work based on discussion in the linked issue?

**Comment by lmoureaux** [comment]
More work is needed, changing back to draft

**Comment by lmoureaux** [comment]
I think this is now working -- it's useless for ChromeOS due to #2137, but could be useful e.g. on a Raspberry Pi

**Comment by jwrober** [comment]
What happens if you drop to Ubuntu 20.04?

**Comment by lmoureaux** [comment]
> What happens if you drop to Ubuntu 20.04?

We no longer support it because of the very old Qt version there

**Comment by lmoureaux** [comment]
@jwrober do we merge this or do you want to wait for #2137?

**Comment by jwrober** [comment]
Since this patch doesn't really do what is intended I am not sure it should be merged. I like the idea of the OBS "resurrection" instead. The number of packages is getting harder to maintain.

**Comment by lmoureaux** [comment]
To be superseded by OBS-based packages, see #2137.

**Pull request closed without merging**
