### PR TITLE
Add Tutorial as a menu option on main page

### LINKED ISSUE #1365: Add the Tutorial Scenario to the Main Start Screen
**Is your feature request related to a problem? Please describe.**
Other games that support a tutorial scenario as a teaching tool to new players have it prominently on the main menu or start screen.

**Describe the solution you'd like**
Add a button to start our Tutorial scenario on the main start screen. The button would automatically start the server with the scenario saved game right away, bypassing the "start scenario" dialog.

**Describe alternatives you've considered**
We could add some text or something pointing out the scenario, but that seems janky.

**Additional context**
I was reviewing The Battle for Wesnoth's documentation and was reminded they have Tutorial scenario at the top of their main menu. Thought it a good idea for us.

### LINKED ISSUE #1375: Move Patches/* to dist/wasm
**Is your feature request related to a problem? Please describe.**
We don't need a patches directory on the top level of the repo for a couple of files specifically for the wasm build. 

**Describe the solution you'd like**
Move them to `dist/wasm` or maybe `dependencies/wasm`.

**Describe alternatives you've considered**
None

**Additional context**
Was mentioned in #1341, breaking out here on it's own.

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1365 

Still needs some refactoring work. Did consolidate the loading of a server to a single function instead of duplicating the same code 3 times.

### CODE REVIEW

**Comment by jwrober** [comment]
This is what the updated main menu looks like now
image

**Comment by lmoureaux** [comment]
I'm *finally* getting to this (now that #1430 is on track)

**Comment by lmoureaux** [comment]
The button works now, handing this back to @jwrober :)

**Comment by jwrober** [comment]
> The button works now, handing this back to @jwrober :)

Thanks @lmoureaux !

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
