### PR TITLE
Support window icons on Wayland

### PR DESCRIPTION
**Pull request by lmoureaux**
On Wayland, window icons are taken from `.desktop` files. This PR adds support for this.

* The client desktop file is renamed to match the one installed by Flatpak
* Desktop file names are provided to `QApplication`

I used the normal desktop file name for the modpack installer; Flatpak installs a different one.
The Flatpak manifest will need small changes to accommodate the renamed files.

### CODE REVIEW

**Review by jwrober — APPROVED** [review]
Agreed. I had to use rename commands to meet the flatpak requirements. We won't need those with this change.

**Comment by lmoureaux** [comment]
> Agreed. I had to use rename commands to meet the flatpak requirements. We won't need those with this change.

Should I also rename the modpack installer desktop file to please the Flatpak gatekeepers?

**Comment by jwrober** [comment]
> Should I also rename the modpack installer desktop file to please the Flatpak gatekeepers?

No it passed muster the first time.

**Comment by lmoureaux** [comment]
> > Should I also rename the modpack installer desktop file to please the Flatpak gatekeepers?
> 
> No it passed muster the first time.

Ah we just [renamed it](https://github.com/longturn/freeciv21/commits/master/dist/net.longturn.freeciv21.modpack.desktop.in) to remove the `-qt` at the end, hence my confusion.

**Pull request merged**
