### PR TITLE
Fix Start game not spawning server on windows

### LINKED ISSUE #341: Windows/Msys2 - freeciv-server when called from freeciv-qt "gets stuck"
Debug console code shown

```
[info] freeciv-qt (unknown:0) - Starting freeciv-server at C:/Program Files/Freeciv21 v3.1.0/freeciv-server.exe
[debug] freeciv-qt (unknown:0) - sending packet type=PACKET_SERVER_JOIN_REQ(4) len=46 to server
[debug] freeciv-qt (unknown:0) - sending request 1
```

@lmoureaux is aware.  If you open a command prompt and run the server by itself it starts fine.

image

### PR DESCRIPTION
**Pull request by mir3x**
Fix #341

### CODE REVIEW

**Comment by mir3x** [comment]
It looks like server was running but not fully loaded and client sent JOIN_REQ already

**Comment by lmoureaux** [comment]
Have you confirmed that this is also working on Linux?

**Comment by mir3x** [comment]
No 👯

**Comment by mir3x** [comment]
> Have you confirmed that this is also working on Linux?

Yes

**Comment by mir3x** [comment]
Added waitForReadyRead back just in case and waitForReadyRead() and waitForStarted() to be sure

**Comment by lmoureaux** [comment]
Many thanks for fixing this!

**Pull request merged**
