### PR TITLE
Client Manual Update

### PR DESCRIPTION
**Pull request by jwrober**
No issue assigned. This is a collection of updates requested from the initial version of the manual.

### CODE REVIEW

**Comment by jwrober** [comment]
Oh, the RTD build failed. It doesn't like the new extension. Hm...

**Comment by lmoureaux** [comment]
Is it Github or did the image size actually increase?
image

**Comment by lmoureaux** [comment]
> Oh, the RTD build failed. It doesn't like the new extension. Hm...

https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file

**Comment by jwrober** [comment]
> Is it Github or did the image size actually increase?

Well it might have increased. I ran all the images through a compressor and didn't look at each one to see if there was any increases.

**Comment by jwrober** [comment]
> > Oh, the RTD build failed. It doesn't like the new extension. Hm...
> 
> https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file

Ok. I'll look at this tomorrow

**Comment by jwrober** [comment]
> > > Oh, the RTD build failed. It doesn't like the new extension. Hm...
> > 
> > 
> > https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file
> 
> Ok. I'll look at this tomorrow

@lmoureaux i got it working -- see https://longturn--1248.org.readthedocs.build/en/1248/General/Manuals/client-manual.html to aid review

**Comment by lmoureaux** [comment]
What's the difference between `city-dialog-general-min.png` and `city-dialog-general.png`?
Same question for `city-dialog-min.png` and `city-dialog.png`. For these, let's not introduce images with a buggy grid.

Please check that the compressed images are indeed smaller, otherwise you're making both the page and the repo heavier :sweat_smile:

**Comment by jwrober** [comment]
> What's the difference between `city-dialog-general-min.png` and `city-dialog-general.png`? Same question for `city-dialog-min.png` and `city-dialog.png`. For these, let's not introduce images with a buggy grid.
> 
> Please check that the compressed images are indeed smaller, otherwise you're making both the page and the repo heavier sweat_smile

I don't see those `-min` files in my local, they should not be there so I don't know how they are in the repo.

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
