### PR TITLE
Add 15 more nations.

### PR DESCRIPTION
**Pull request by Rorr4**
This is including the 5 by me (Alaska, Dagestan, Donetsk, Luhansk, and Toki Pona) and the 7 by Sketlux (Austria-Hungary, Congo Free State, German Empire, Hesse-Darmstadt, Rhodesia, Saar Protectorate, and Schaumburg-Lippe)

### CODE REVIEW

**Comment by lmoureaux** [comment]
The reason that stopped my effort in integrating Sketlux's nations was that descriptions were taken from Wikipedia, and we need to provide attribution for this content under the CC-BY-SA 4.0 license. Did you take any steps to do this?

**Comment by Rorr4** [comment]
> The reason that stopped my effort in integrating Sketlux's nations was that descriptions were taken from Wikipedia, and we need to provide attribution for this content under the CC-BY-SA 4.0 license. Did you take any steps to do this?

I could either rewrite all the descriptions for the all the nations except Alaska and Toki Pona (I didn't copy the description from Wikipedia) or just add attributions to the nations.

**Comment by lmoureaux** [comment]
> I could either rewrite all the descriptions for the all the nations except Alaska and Toki Pona (I didn't copy the description from Wikipedia) or just add attributions to the nations.

Either way would be fine for me, go with what's easiest for you

**Comment by Rorr4** [comment]
Wait I did the math wrong.

**Comment by Rorr4** [comment]
Going to close this as I had looked through Sketlux's nations and added attributions for the ones that more closely resembled Wikipedia articles, and I also forgot to add the ruleset file for the german empire.

**Pull request closed without merging**
