### PR TITLE
Use native compression tools instead of git archive for releases

### LINKED ISSUE #2179: Release workflow: Wrong version in AutoRevision.txt for v3.0-patch.3
**Describe the bug**
The [release source archive](https://github.com/longturn/freeciv21/releases/download/v3.0-patch.3/Freeciv21-v3.0-patch.3.tar.gz) for `v3.0-patch.3` contains the following:

```sh
cat Freeciv21-v3.0-patch.3/cmake/AutoRevision.txt
f5eab4
v3.0-patch.2
```

**To Reproduce**
- Dowload and inspect the [release source archive](https://github.com/longturn/freeciv21/releases/download/v3.0-patch.3/Freeciv21-v3.0-patch.3.tar.gz)
- Inspect the tag for `v3.0-patch.3` which also contains the wrong version info in [`AutoRevision.txt`](https://github.com/longturn/freeciv21/blob/v3.0-patch.3/cmake/AutoRevision.txt#L2)

**Expected behavior**
`AutoRevision.txt` should contain the correct information, like the file content committed in [4c161dc](https://github.com/longturn/freeciv21/commit/4c161dc8a1cc4b7cbcd505e8be4653bb58a12b66):
```
e5a21
v3.0-patch.3
```

**Platform and version (please complete the following information):**
 - OS: FreeBSD 14.0
 - Freeciv21 version: 3.0-patch.3

### PR DESCRIPTION
**Pull request by jwrober**
Closes #2179

### CODE REVIEW

**Comment by lmoureaux** [comment]
Does this exclude the same files as git-archive? Packaging the whole `data` results in quite heavy tarballs

**Comment by jwrober** [comment]
You get ~100mb files. I can add more excludes if needed. What in data do we not want to ship?

**Comment by jwrober** [comment]
I pulled data/graphics out. Now the archives are around 50mb

**Comment by jwrober** [comment]
Works as expected on my fork
https://github.com/jwrober/freeciv21/actions/runs/8500972813/job/23283394633

**Comment by lmoureaux** [comment]
These are the `export-ignore` from `.gitattributes`:
```
# don't export these files
data/graphics/**    export-ignore
.coverity/**        export-ignore
.github/**          export-ignore
.gitlab-ci.yaml     export-ignore
.readthedocs.yaml   export-ignore
```

**Comment by lmoureaux** [comment]
An alternative approach would be to commit the autorevision changes and keep using `git archive`

**Comment by jwrober** [comment]
We get all of those w/ `git archive` too, so I don't see an issue there.

**Comment by jwrober** [comment]
My solution doesn't pull those in.

**Comment by lmoureaux** [comment]
Interesting :joy: I see `.coverity` (empty dir) and `.gitlab-ci.yml` in the latest tarball, but not the other two.
With your solution we don't package any hidden file, which works as well

**Comment by jwrober** [comment]
I did see an issue in the zip file. Since it runs after the gz creating it also pulls in the sha file. I'll push a fix

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
