### PR TITLE
Cherry pick freeciv.org music fixes

### LINKED ISSUE #375: Merge Freeciv 2.6.x Music commits to Freeciv21 Master
Need to evaluate this commit to overall function of music play in fc21

https://github.com/longturn/freeciv21/commit/a2a215fe9dd41aacac869e767dba5f6e813f9b59

The following commits from legacy freeciv will make music play work much better in freeciv21

https://github.com/freeciv/freeciv/commit/a9d4a4dd054d5320bc1afa44b913fd7e3c82a66b
https://github.com/freeciv/freeciv/commit/e355db22740839b9048a4e6648965a71a7651442
https://github.com/freeciv/freeciv/commit/6b50a5b0bc6650d4c03992aa1fa71643c26fb5ed
https://github.com/freeciv/freeciv/commit/2b24adcae463e4c646c804b82a1f7610008288d0
https://github.com/freeciv/freeciv/commit/ff2462fa627cb48cf8ee34d0736381065c941fb4

### PR DESCRIPTION
**Pull request by lmoureaux**
Closes #375.

Two commits cancelling each other were not included and another related fix was also included.

@jwrober I'd be grateful if you could confirm that the issues are fixed.

### CODE REVIEW

**Comment by jwrober** [comment]
@lmoureaux The email I get when I was mentioned includes links to a .diff and .patch files. Is that I will apply to my local tree to test this out?

**Comment by lmoureaux** [comment]
Depends on the patches… I'll run a search. You can apply the .diff if you prefer working with files; if you like git you can add my remote and checkout the branch:
```
git remote add louis94 git@github.com:lmoureaux/freeciv21.git
git fetch louis94
git checkout louis94/bugfix/cherry-pick-freeciv-org-music-fixes
```

**Comment by lmoureaux** [comment]
Imported one more cazfi patch. The last one is a capstring bump which I'm not sure if we want (need to decide how to handle capability strings and versions in general).

**Review by jwrober — APPROVED** [review]
I pulled the .diff link provided by the email. It contained all the commits. I applied to my local and build the whole system. Music plays very well. I think this is ready to commit.

**Pull request merged**
