### PR TITLE
Check cache fc_version.h at configure time

### LINKED ISSUE #1564: fc_version.h not updated automatically
**Describe the bug**

fc_version.h isn't updated automatically when fc_version.h.in is modified or the version changes, potentially leading to inconsistent builds.

**To Reproduce**
1. Build fc21
3. Modify fc_version.h.in
5. Rebuild (do **not** do a clean build)
7. Nothing is rebuilt

**Expected behavior**
fc_version.h gets updated and many files get rebuilt.

**Platform and version (please complete the following information):**
 - OS: all
 - Freeciv21 version: 3.0-beta.6

**Additional context**
This caused issues updating the server at longturn.net.

### PR DESCRIPTION
**Pull request by jwrober**
For devs who do not clean their cache directory often, we do a check for the generated `fc_version.h` and if the patch version is different then we delete the cache file. Closes #1564

### CODE REVIEW

**Comment by lmoureaux** [comment]
I'm afraid that this will trigger a full rebuild after every local commit, which is definitely too much, but maybe I misremember what we put in the version string?

**Comment by jwrober** [comment]
> I'm afraid that this will trigger a full rebuild after every local commit, which is definitely too much, but maybe I misremember what we put in the version string?

I didn't test that scenario. Let me see what happens.

**Comment by jwrober** [comment]
It works while you are working on a bunch of local changes. Multiple commits are fine in a branch while you are working. You might run into an issue if you switch to a different branch that has a diff hash from master branch, that will force a "mostly" recompile, but not a total recompile. The code is essentially getting the current hash turned into a integer from the last pull, so based on what that is in the branch you are working on would cause a recompile. I think this better than ignoring it altogether like we did in the past. One recompile with a fresh `git pull` is not horrible.

**Comment by lmoureaux** [comment]
> You might run into an issue if you switch to a different branch that has a diff hash from master branch, that will force a "mostly" recompile, but not a total recompile. 

I switch between branches all the time, so this will slow me down significantly :( I think we keep this out for now and revisit after 3.0 is out, moving the info to a file that gets compiled exactly once (and fast).

**Comment by jwrober** [comment]
Yea I was thinking something about that too. I wonder if it would be better to check the tag and do the removal of the cached file when a new tag is done. That would be a more rare event and allow branch switching.

**Review by lmoureaux — CHANGES_REQUESTED** [review]
Just to prevent immediate merge

**Review by lmoureaux — APPROVED** [review]
Fixed my concerns and rebased for the new CI checks

**Pull request merged**
