### PR TITLE
Restore NLS in the Windows CI

### LINKED ISSUE #420: Re-enable NLS in the Windows CI
CMake 3.20.1 has been released and is included in the MinGW distribution, fixing issue #383. As a consequence, NLS should now work on the Windows CI and can be enabled.

### PR DESCRIPTION
**Pull request by lmoureaux**
Closes #420.

### CODE REVIEW

**Comment by lmoureaux** [comment]
Probably too early.

**Comment by jwrober** [comment]
@lmoureaux Is there a way to have Travis try again against what is in master branch now?

**Comment by lmoureaux** [comment]
Rebased to trigger a new Travis build.

**Comment by lmoureaux** [comment]
Windows build passed!

**Pull request merged**
