### PR TITLE
Support fc21:// links on Linux

### PR DESCRIPTION
**Pull request by jwrober**
Part 1 of 3 in #916

### CODE REVIEW

**Comment by jwrober** [comment]
To test this. Install the code, drop `share/applications/net.longturn.freeciv21.client.desktop` to `~./local/share/applications`. Then save this html to your computer:

```
<html>
<title>fc21 link tester page</title>
<body>
<p>Link to a Freeciv21 Game: <a href="fc21://localhost:9999">LT9999</a></p>
</body>
</html>
```

Start a server on port 9999, open the saved html page and click the link.

**Comment by jwrober** [comment]
You might need to run `update-mime-database` for the new `.desktop` file to register the new protocol, or you could reboot at worst case.

**Comment by lmoureaux** [comment]
Should this be documented somewhere? (Not necessarily for this PR)

**Comment by jwrober** [comment]
> Should this be documented somewhere? (Not necessarily for this PR)

Probably in some kind of game administrator's guide? The likely usage is on our longturn.net website game pages.

**Comment by lmoureaux** [comment]
Could go in `Freeciv21 on the Server` indeed

**Review by lmoureaux — APPROVED** [review]
Works for me with the deb installer

**Pull request merged**
