### PR TITLE
Unhardcode unit healing

### PR DESCRIPTION
**Pull request by ec429**
Replace the hardcoded extra healing in `hp_gain_coord()` with a new bonus `EFT_HP_REGEN_MIN`, which supplies the minimum (as a percentage of unittype's HP) to clamp to.
This PR currently includes updates to the Classic ruleset to replicate the old hardcoded behaviour, but does not (yet) update the other rulesets, nor touch ruleup.
Testing: build only so far.

Closes longturn#593.

### CODE REVIEW

**Comment by lmoureaux** [comment]
Looking at this more, it looks like the `max()` can already be implemented in `effects.ruleset`. It requires less C++ but maybe a lot more ruleset code?

Code itself looks good. Nitpicking that you could use `std::max()` instead of `MAX()` but `MIN()` and `MAX()` are used everywhere anyway, I'll probably do a mass replace sometime.

Use the following to your description to trigger [Github automation rules](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword): `Closes #593`.

Next on the todo list from my point of view:

* [ ] Add the new effect to `docs/Modding/Rulesets/effects.rst`
* [ ] Decide on a strategy for ruleset compatibility. Since 1) we're still in alpha, 2) SIM30 uses ruleup, and 3) I trust Avi will be updated in a timely manner, I think a breaking change is acceptable (@jwrober thoughts?). This would be done by updating shipped rulesets and bump the ruleset capstring. We'll want to update the modpack installer content immediately after the release.
  The alternative is to call this a new format version and enable automatic `ruleup` in the server. I'm not sure why it's currently disabled, any background info on that would be welcome.
* [ ] Ruleup uses [this god function](https://github.com/longturn/freeciv21/blob/master/server/rscompat.cpp#L652)

**Comment by jwrober** [comment]
The classic ruleset seems to be updated. So if we don't update any of the other ones that ship with the two packages they would break with this change? I'm not sure I am a fan of that. Looks like it is a bit of CnP into the other ruleset files to bring them up to speed and not break existing rules on our way to Beta 1.

**Comment by lmoureaux** [comment]
> The classic ruleset seems to be updated. So if we don't update any of the other ones that ship with the two packages they would break with this change?

It is my understanding that this will be done once the rest is decided upon, this PR is still a draft. My concern is more about compatibility with other rulesets (SIM and Avi).

**Comment by ec429** [comment]
@lmoureaux is right, I plan to update the rest of the bundled rulesets for the 'final' PR.  I just wanted to get something up as an RfC so folks could start reviewing the code side.

Regarding ruleup, how about adding in compat effects if there is no `EFT_HP_REGEN_MIN` defined in the ruleset?  Rulesets wanting to suppress that but still not have the `MIN` could have an effect with value 0.  It wouldn't be perfect, as there's no way I can see to automatically test for `hp_loss_pct!=0`, but it'd mean un-fixed rulesets were _mostly_ compatible and wouldn't need a capstring break / flag day.

Regarding Avi, I plan to use this to make city HP regen depend on having a suitable building in the city — jets will require the same Air Base that's needed to build them, while for heavy props (e.g. Lancasters) I'll have a new Concrete Runway impr (that won't be required for build, since upgrade would bypass that).

**Comment by ec429** [comment]
It occurs to me that the `Unit_Recover` we use to simulate rounding-up behaviour isn't quite a perfect match, because it applies even if unit moved this turn.  Possible alternatives:

- Lots of extra HP_Regen effects conditioned on unit flags, that add just the right amount of extra percents to make each unit DTRT.  (This is ugly.)
- Change `hp_gain_coord()` to round up when applying the regen: `hp = (base - 1) * bonus / 100 + 1;`.  This is technically a semantic change, would e.g. make 10-hp units in Fortresses (regen=25%) gain 3HP/turn instead of 2.  (But I think that's acceptable.)

**Comment by lmoureaux** [comment]
I think that off-by-one differences is an acceptable tradeoff they don't change 1 -> 0 or 0 -> 1.

> Regarding ruleup, how about adding in compat effects if there is no EFT_HP_REGEN_MIN defined in the ruleset? Rulesets wanting to suppress that but still not have the MIN could have an effect with value 0. It wouldn't be perfect, as there's no way I can see to automatically test for hp_loss_pct!=0 (edit: or hitpoints not divisible by 10), but it'd mean un-fixed rulesets were mostly compatible and wouldn't need a capstring break / flag day.

This solution looks overly complicated and somewhat counterintuitive for ruleset authors. Testing for `hp_loss_pct != 0` (resp. `HP % 10 != 0`) is definitely possible by iterating over unit classes (resp. unit types). I would suggest to using the proper migration feature that one of the Freeciv devs grafted us with years ago and that was never really used: capabilities. Add a new optional capability to the ruleset capstring, and automigrate rulesets that don't define it. We can then make it implicit for ruleset version 30 when it comes. Getting this to work will likely require small changes all over the place, I'm happy to help.

I also noticed that the path finding code has some support for units losing HP (helicopters in classic rulesets). I don't think it's worth adding support for the new effect there (it is broken in other ways regarding effects: for instance, in LTT units will happily end their turn on mountains because it's safer, but all calculations are off because the code doesn't know that it also means losing one MP for the next turn).

**Comment by ec429** [comment]
I've implemented the "round up" behaviour, and changed the ruleset patches accordingly.
I'll leave automigration for someone else to do, because while capabilities sound like the right thing, it also sounds like they've likely bitrotted and I don't feel like wrestling that.
I've also still not properly tested this (other than messing about in a SP Avi game bombing the AI and watching units heal or not).  I'm not super sure how to rigorously test it.

Regarding hp_loss_pct, I almost feel like that should be replaced with an HP_Loss effect (which could then be given reqs like "unitclass heli; citytile center !present; extra airbase !present" to replicate the old behaviour).  But that's just a suggestion for the future if someone wants to do something more detailed (because unhardcoding is a Good Thing).

**Comment by lmoureaux** [comment]
> I also noticed that the path finding code has some support for units losing HP (helicopters in classic rulesets)…

-> #824 will pick it up automatically, but the AI won't be aware until it's ported away from the old PF

**Comment by lmoureaux** [comment]
Added the migration code, I think you missed `CityCenter` in the requirements for `HP_Regen_Min`.

**Review by lmoureaux — APPROVED** [review]
Elsewhere:
> technically 4 and 5 don't need the CityTile Center req, because if it's not a city then `EFT_HP_REGEN` and `EFT_HP_REGEN_MIN` will be the same (e.g. 20 if fortified and not `hp_loss_pct`).  Which is why I didn't add them to the existing rulesets

Sounds good :+1:

**Review by jwrober — APPROVED** [review]

**Pull request merged**
