### PR TITLE
Fix a few path finding bugs

### LINKED ISSUE #1360: The path finding code believes that disembarking always uses up full MP
**Describe the bug**

Some units (e.g. airplanes) can unload from transports without losing full MP. The path finding code thinks they lose them and displays turn steps incorrectly.

**To Reproduce**
1. Load a fighter on an aircraft carrier (classic ruleset), make sure the fighter has MP left
2. Select the fighter
3. Do `g`
4. Move the mouse around and look at the first goto step (always next to the carrier)

**Expected behavior**

TC marks reflect reality.

**Screenshots**

This Bomber has 4 MP left, there shouldn't be a TC marker next to the Carrier
image

**Platform and version (please complete the following information):**
 - OS: Irrelevant
 - Freeciv21 version: 3.0-beta4+
 - Ruleset/Longturn game (if applicable): `classic`

### PR DESCRIPTION
**Pull request by lmoureaux**
Fix three rather stupid bugs due to rapid development of the path finding algo, including #1360.

~~**Bug:** unloading foot soldiers from a boat gives incorrect results now :(~~

Closes #1360.

### Testing

I tested unloading bombers and fighters from a carrier and dropping paratroops.

### CODE REVIEW

**Review by jwrober — APPROVED** [review]
Works for me

**Comment by jwrober** [comment]
Oh I see this is a draft. You expecting to push more commits?

**Comment by lmoureaux** [comment]
> Oh I see this is a draft. You expecting to push more commits?

Yes, I asked for the review too early, sorry about that. I need to fix a bug when unloading units to the shore.

**Comment by lmoureaux** [comment]
Bug fixed: foot soldiers disembarking from a ship are now handled correctly.

**Review by jwrober — APPROVED** [review]

**Pull request merged**
