### PR TITLE
Bump top bar icons to 22px

### LINKED ISSUE #1254: Increase the size of the icons on the buttons on the top bar
**Is your feature request related to a problem? Please describe.**
We have some really great icons on the buttons on the top bar. I would like to see them larger to make it more pronounced. This is a sample of what they look like now:

image

**Describe the solution you'd like**
Change the icons so they fill most (~80%) of the height of the button. I think the font size does not need to change.

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by lmoureaux**
Closes #1254.

### CODE REVIEW

**Comment by jwrober** [comment]
What is so magical about 22px? Where do we set the height of the top bar? At 22px, the icons are still quite small. I was looking for the icons to be much larger - e.g. make them much more prominent and fill a large portion of the height of the top bar. Even with the gui as small as I can get it on my laptop, I still think the icons could be bigger

image

**Review by jwrober — CHANGES_REQUESTED** [review]
See comment

**Comment by lmoureaux** [comment]
The height of the top bar is a function of the font size. 22px is a about the height of two lines of text at a size of 12px. Making icons taller also implies making them wider, without changing the horizontal space between the icon and the text, so this starts to look strange if you make them very large. 22px looked "right" on my display.

**Review by jwrober — APPROVED** [review]
I played around with the value on my local. 30px seems like a good number too, but I'm not going to quibble over 8px. This is still better than it was.

**Comment by lmoureaux** [comment]
Let's revisit after #1287

**Comment by lmoureaux** [comment]
So what do you think with the new colors?

**Comment by jwrober** [comment]
> So what do you think with the new colors?

I still think they could be bigger. I do still like 30px. I also see something weird with the nations view button. The icon is missing or oddly small for some of the themes

image
image

**Comment by lmoureaux** [comment]
> I also see something weird with the nations view button. The icon is missing or oddly small for some of the themes

It's a fixed-size png, not a scalable icon

**Pull request merged**
