### PR TITLE
Refactored tilespec.cpp code. Part of the progress on #2232

### PR DESCRIPTION
**Pull request by hugomflavio**

### CODE REVIEW

**Comment by hugomflavio** [comment]
@jwrober we need you to review this one, please :)

Not sure what the clang check is complaining about, I ran clang before committing :thinking:

**Comment by jwrober** [comment]
Me either. I can take a look this afternoon

**Comment by lmoureaux** [comment]
> Not sure what the clang check is complaining about, I ran clang before committing 🤔

Looks like the classic issue of a `clang-format` version mismatch. We use v11 which is getting old

**Comment by jwrober** [comment]
I'm getting warnings

```
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching unit.action_decision_want
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching city.size_000
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching path.turns_000 or city.size_000
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching path.steps_000, path.turns_000, or city.size_000
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching path.exhausted_mp_000, path.turns_000, or city.size_000
[info] freeciv21-client ( /tilespec.cpp:1004) - Loading tileset "amplio2".
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching unit.action_decision_want
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.road_c_ne
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.road_c_se
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.road_c_sw
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.road_c_nw
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.rail_c_ne
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.rail_c_se
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.rail_c_sw
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.rail_c_nw
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.maglev_c_ne
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.maglev_c_se
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.maglev_c_sw
[warning] freeciv21-client ( /tilespec.cpp:412) - Could not find optional sprite matching road.maglev_c_nw
```

Is this expected?

**Comment by hugomflavio** [comment]
Looks like part of the new, improved warnings we implemented. Notice all of
those are "optional" sprites. Which tileset are you using? I can have a
closer look later.

**Comment by hugomflavio** [comment]
Do you get those warnings for hexemplio?

**Comment by hugomflavio** [comment]
```Could not find optional sprite matching city.size_000```

These look like real bugs though. Pretty sure that should end in 100?

**Comment by lmoureaux** [comment]
> `Could not find optional sprite matching city.size_000`
> 
> These look like real bugs though. Pretty sure that should end in 100?

I bet there is no 000 sprite because it would only be used starting from 1000, which isn't supported

**Comment by jwrober** [comment]
Aplio2 Debugger
image

**Comment by jwrober** [comment]
Hexemplio Debugger
image

**Comment by hugomflavio** [comment]
@lmoureaux do you recall if there were warnings for optional sprites before?

**Comment by lmoureaux** [comment]
> @lmoureaux do you recall if there were warnings for optional sprites before?

There weren't, we may want to downgrade to info

**Comment by hugomflavio** [comment]
Make it a note? Sounds good by me

**Pull request merged**
