### PR TITLE
Fix research refresh button

### LINKED ISSUE #1753: Make it possible to forcibly research a tech that is instantly researchable after TC due to tech leak
**Is your feature request related to a problem? Please describe.**
Currently, if RNGeezus wants, a player may end up in a situation where they have more bulbs stored than their current research target costs, due to tech leak. This happens due to player processing order, where a player might gain just-not-enough bulbs to research a tech, but a player processed later might have enough, causing the cost to drop due to tech leak. Sometimes you can then "force" the game to research the tech by switching to another one that's sufficiently expensive (so you don't insta-research it and lose your bulbs) and then switching back, forcing the server to process the research. This may not always be possible, forcing the player to wait until next TC.

**Describe the solution you'd like**
Two potential solutions:
1. Make the server somehow find out if tech leak would affect players that have already been processed, and process their research again (this might do weird stuff with obsoletions and stuff, I don't know the exact sequence of events in the TC sequence)
2. Quite a bit simpler, when the player sets their tech goal to the one they're currently researching, the server accepts this and processes it as if the player switched to any other tech. I'm pretty sure this would mean just removing lines 1020-1022 in `techtools.cpp`, but this is only from a cursory search. It does appear that the client sends the "switch research" packet even when the player clicks on a tech they're currently researching.

**Describe alternatives you've considered**
Leaving it as-is...

**Additional context**
No additional context

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1753

Marking as draft for now. Need an event to test it.

### CODE REVIEW

**Comment by lmoureaux** [comment]
I doubt this will work, `handle_player_tech_goal` in `server/techtools.cpp` doesn't seem to set the current tech.

Moreover, this would wipe out any tech goal previously set by the user.

**Comment by jwrober** [comment]
Ouch. Well glad I pushed this draft before I blew out a turn giving a test.  Ideas on what to try next?

**Comment by lmoureaux** [comment]
See my comment on the issue. Try removing this line... but you need to set up a local test :)

**Comment by jwrober** [comment]
That has been my biggest problem. I have not been able to get a local save with the "problem" in it to test locally.

**Comment by lmoureaux** [comment]
[save.zip](https://github.com/user-attachments/files/16955683/save.zip)

**Comment by jwrober** [comment]
I never thought about hacking a save file. Nice. The suggestion works great.

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
