### PR TITLE
Change the Nations button blink to a gentle notification emblem

### LINKED ISSUE #1676: Create an option to enable/disable the binking Nations and Research view buttons
**Is your feature request related to a problem? Please describe.**
There seems to be some disagreement on the effectiveness of the Nations view and Research view buttons that blink/pulse to remind the player that something needs their attention.

**Describe the solution you'd like**
In stead of getting rid of it, since it was asked for - simply add some options. One for each to enable/disable the blinking/pulsing. I would suggest they are enabled by default.

**Describe alternatives you've considered**

**Additional context**
Discord - https://discord.com/channels/378908274113904641/912500712833974322/1059195496238940180

### PR DESCRIPTION
**Pull request by lmoureaux**
This minimizes the annoyance while still hinting that something in the tab is active. The notification icon uses the same design as in the Messages button.

Closes #1676.
Backport candidate.

### CODE REVIEW

**Comment by jwrober** [comment]
The overall change is more appealing and does match the messages icon. however i think the change is missing a refresh. after canceling two meetings... i would expect to see base flag.
image

**Comment by lmoureaux** [comment]
Opened two meetings, restarted the client, closed them:
image
The icon you see is strange, any idea where it comes from?

**Comment by jwrober** [comment]
It looks like an artifact of the old image with the dot on it. Is there a way to clear the old icon as part of the refresh?

**Comment by jwrober** [comment]
Another point of note, I left one savegame with the icon "bad" and then opened another savegame and the icon did not revert to "no meetings" mode, it was still in a bad state.

**Comment by lmoureaux** [comment]
> Another point of note, I left one savegame with the icon "bad" and then opened another savegame and the icon did not revert to "no meetings" mode, it was still in a bad state.

Would you have the save?

**Comment by jwrober** [comment]
This is the first save that I have that starts with two meetings at load.
[freeciv21-T0325-Y01877-auto-LateTestGame.sav.gz](https://github.com/longturn/freeciv21/files/10366691/freeciv21-T0325-Y01877-auto-LateTestGame.sav.gz)

This is the second one I did in my last comment that started with the "artifact"
[freeciv21-T0048-Y-1650-manual.sav.gz](https://github.com/longturn/freeciv21/files/10366693/freeciv21-T0048-Y-1650-manual.sav.gz)

**Comment by jwrober** [comment]
Ok something is up with my local. I was looking at icon files for the PR on allies button and noticed this
image

So somehow my `flag.svg` got messed up.

**Comment by jwrober** [comment]
The resize of `flag.svg` get's corrupted on my local when I bring down the patch for testing. I wiped my local to get it "clean" and when I run the eval screen my local copy of `flag.svg` is corrupted to the image above. I think the resize needs some work I guess, or just leave it as it was as it worked fine before.

**Review by jwrober — CHANGES_REQUESTED** [review]
See comment above

**Comment by lmoureaux** [comment]
Can't see anything in the svg that would cause this issue. Is the file partially merged?
```
$ md5sum data/themes/gui-qt/icons/flag.svg
9d1e89c654f16e03c59ffa4829a17237  data/themes/gui-qt/icons/flag.svg
```

**Comment by lmoureaux** [comment]
Changes to `flag.svg` reverted.

**Comment by lmoureaux** [comment]
(For the record, this is [a QtSvg bug](https://bugreports.qt.io/browse/QTBUG-92184))

**Review by jwrober — APPROVED** [review]
How do I find all the upstream bugs?! Reverted `flag.svg` works great.

Backport candidate recommended.

**Comment by lmoureaux** [comment]
> How do I find all the upstream bugs?!

I looked at the commit log between your QtSvg and mine (which has the bug fixed). There were like 3 changes, and only one commit message looked relevant.

**Comment by jwrober** [comment]
I'm going to document the change in another PR, so merging this now.

**Pull request merged**
