### PR TITLE
Nix packaging and CI

### PR DESCRIPTION
**Pull request by lmoureaux**
Supersedes #1897 (I can't edit the branch): Removed the MacOS attempt (stuck on building KArchive) and switched the build to weekly.

### CODE REVIEW

**Review by jwrober — APPROVED** [review]
LGTM

**Comment by dmadisetti** [comment]
Oh cheers. Thank you. Sorry I dropped the ball. Appreciate it!

Were you able to test it beyond the CI?

**Comment by lmoureaux** [comment]
It doesn't seem to work with Nix 2.6.0 from the Ubuntu archives. `nix build` fails with:
```
error: flake 'github:longturn/freeciv21' does not provide attribute 'packages.x86_64-linux.defaultPackage.x86_64-linux', 'legacyPackages.x86_64-linux.defaultPackage.x86_64-linux' or 'defaultPackage.x86_64-linux'
```
and `nix run` with:
```
error: cannot find flake attribute 'github:longturn/freeciv21#defaultApp.x86_64-linux'
```

**Comment by dmadisetti** [comment]
Try `nix run --no-write-lock-file github:longturn/freeciv21#`. It's compiling for me right now

**Comment by lmoureaux** [comment]
```
$ nix run --no-write-lock-file 'github:longturn/freeciv21#'
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
$ nix run --no-write-lock-file 'github:longturn/freeciv21#' --extra-experimental-features nix-command
error: getting status of /nix/var/nix/daemon-socket/socket: Permission denied
$ sudo nix run --no-write-lock-file 'github:longturn/freeciv21#' --extra-experimental-features nix-command
error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
$ sudo nix run --no-write-lock-file 'github:longturn/freeciv21#' --extra-experimental-features nix-command --extra-experimental-features flakes
warning: not writing modified lock file of flake 'github:longturn/freeciv21':
• Added input 'flake-utils':
    'github:numtide/flake-utils/cfacdce06f30d2b68473a46042957675eebb3401' (2023-04-11)
• Added input 'flake-utils/systems':
    'github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e' (2023-04-09)
• Added input 'nixpkgs':
    'github:NixOS/nixpkgs/cc45a3f8c98e1c33ca996e3504adefbf660a72d1' (2023-05-04)
error: cannot find flake attribute 'github:longturn/freeciv21#defaultApp.x86_64-linux'
```

**Comment by dmadisetti** [comment]
Ok, makes sense
```
nix --version                                                                                                                                                                                                         
nix (Nix) 2.13.3
```

I think there's a way of making it backwards compatible, but explicitly doing "github:longturn/freeciv21#freeciv21" should work. Sorry should have thought about older nix versions. We can update the readme accordingly, I'll see if I can downgrade to test as well

**Comment by dmadisetti** [comment]
Confirmed that `nix run --no-write-lock-file github:longturn/freeciv21#freeciv21` works with 2.6

**Comment by lmoureaux** [comment]
Yes it works (if I add the experimental features)! You don't include `sudo`, is there a way to not run it as root?
I'm not sure if we should update the instructions. Debian/Ubuntu users are expected to use `dpkg`. Fedora doesn't seem to have a package. Is there any downside to the longer command?

**Comment by dmadisetti** [comment]
Re sudo: If using as a package manager, you need to create and be part of the `nixbld` [group](https://nixos.org/manual/nix/stable/installation/multi-user.html). On NixOS it's built in

No, the longer command just turns on the flags to make flakes work. They should work out of the box relatively soon (maybe >2.6? not sure when).
--no-write-lock-file is required because we don't include the `flake.lock` (similar to a `cargo.lock` or `package.lock` for rust and js respectively), but the error is self explanatory, and the lock file doesn't really matter since we are pinning to 22-11 in the flake anyway.

**Pull request merged**
