### PR TITLE
Cleanup Docs

### PR DESCRIPTION
**Pull request by jwrober**
Collection of commits to clean up the `/docs` files after all the legacy files in `doc` were converted. Also moved some files around to be ready for other documentation issues to be completed in the near future.

### CODE REVIEW

**Review by lmoureaux — COMMENTED** [review]
`Developing/Coding` sounds redundant and `Developing/Contributing` sounds like it should be the other way around. What's the rationale for the new structure? What will eventually it look like?

**Comment by jwrober** [comment]
> What's the rationale for the new structure? What will eventually it look like?

Contributing is for non-coders (people like me who don't get deep into the `cpp` code, QT framework, AI coding, etc. Documents here are related to the PR process, Release process, getting involved w/ issues, etc. I foresee the list of documents here to be smaller and mostly static once I get the list of issues closed.

Coding is then the opposite of Contributing. This is where the hacking guide, AI, FCDB, and other code related documents go. I can see that this directory will get a lot of documents as we expose more details to the code to the community. I think the more we are open about the code and how to contribute there is going to help a lot.

**Comment by lmoureaux** [comment]
I would see something like this…

* Contributing
  * General
  * Translations
  * Code
  * …
* Technical documentation
  * AI
  * FCDB
  * Whatsnot

**Comment by jwrober** [comment]
Ok let me do another commit

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
