### PR TITLE
Bundle the freefont package in dist

### PR DESCRIPTION
**Pull request by jwrober**
Part 1 of 2 of #1292. Once this is merged, then I can update the varying packages. Linux will use a package dep, while Windows and macOS will need the files copied to the installer.

### CODE REVIEW

**Comment by lmoureaux** [comment]
What do the fonts look like in context?

**Comment by jwrober** [comment]
Good question. With these settings as an example:
image

You get...
image
image
image
image
image

**Comment by jwrober** [comment]
I forgot research tree
image

**Comment by lmoureaux** [comment]
FreeMono feels out-of-place. Are the others bold?

**Comment by jwrober** [comment]
> FreeMono feels out-of-place. Are the others bold?

No, all are "regular". This is what bold mono looks like
image

**Comment by jwrober** [comment]
After a discussion on Discord. We are going to go with a different font set.

**Pull request closed without merging**
