### PR TITLE
Fix and modernize listener<>

### PR DESCRIPTION
**Pull request by lmoureaux**
Commit d1f50af71316b3ab817f0438aecd0a639a93af63 broke the listener<> template in a subtle way: the destructor wouldn't remove listeners from the set because dynamic_cast to a derived type returns nullptr in a destructor. This caused a segfault upon saving map images.

In order to solve both the warning that lead to the commit and the new bug, change the set of instances to hold listener<A>* instead of A*, and use dynamic_cast in invoke since the A objects are still valid there.

While I was there, I changed invoke() to be a variadic template. It wasn't one because the code originally had to support C++03.

### CODE REVIEW

**Comment by lmoureaux** [comment]
Backport required - or at least revert the equivalent of https://github.com/longturn/freeciv21/commit/d1f50af71316b3ab817f0438aecd0a639a93af63 in `stable`

**Review by jwrober — APPROVED** [review]
Looks good. Do we need to worry about the warning from the macOS CI?

**Comment by blabber** [comment]
> Looks good. Do we need to worry about the warning from the macOS CI?

I see these in FreeBSD too. This is nothing to worry about in my opinion. The cause is that macOS and FreeBSD use clang/LLVM as the default compiler.

One could conditionalize the warning using something like this, I am not sure if it is worth it though:

`#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif`

**Comment by lmoureaux** [comment]
> Looks good. Do we need to worry about the warning from the macOS CI?

Further improving the code helped removing the warning.

**Review by jwrober — APPROVED** [review]

**Pull request merged**
