### PR TITLE
Unit selector update

### PR DESCRIPTION
**Pull request by lmoureaux**
This closes the following issues:

* A crash I noticed during testing, quite frequent
* #599 
* #738 

Did a small amount of code cleanup along the way.

Test plan: play with stacked units.

### CODE REVIEW

**Comment by jwrober** [comment]
This fixes issue 599, but not 738. If you have a couple units stacked and move your mouse over the units over and over again the text stacks on top of itself.

**Comment by lmoureaux** [comment]
> If you have a couple units stacked and move your mouse over the units over and over again the text stacks on top of itself.

Could not reproduce this in my testing (start game, look at a stack with settler, worker, explorer). Can you provide more details?

**Comment by lmoureaux** [comment]
Hopefully the issue seen in the picture below (reported by jwrober, system theme) no longer happens.
image

**Review by jwrober — APPROVED** [review]
Looks good now.

**Pull request merged**
