### PR TITLE
Break infinite update() loop in sidebar

### LINKED ISSUE #782: 100% CPU usage
**Describe the bug**

The client uses 100% CPU

**To Reproduce**
1. Start a game
2. Open system monitor
3. Look at CPU usage

**Expected behavior**

Low to moderate CPU usage.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: master as of today
 - Ruleset/Longturn game (if applicable): any

### PR DESCRIPTION
**Pull request by lmoureaux**
Resulted from misuse of the Qt APIs. Use them more as intended.

Closes #782.

Test plan:
* Start game
* Check CPU usage (should be << 100%)
* Check that the sidebar still updates correctly

### CODE REVIEW

**Comment by lmoureaux** [comment]
Rebased for clang-format CI fix, no other change

**Comment by jwrober** [comment]
This is what I see with this patch. 
image

**Comment by hugomflavio** [comment]
I'm still getting >100% CPU usage as well

image

**Comment by lmoureaux** [comment]
I can reproduce 100% CPU when a unit is selected. Going to fix this too.

**Comment by lmoureaux** [comment]
Fixed another source of high CPU usage

**Review by jwrober — APPROVED** [review]
Do get a short spurt of 100% when moving around the map, but that is expected.

**Pull request merged**
