### PR TITLE
Add detailed info about tech progress to top bar

### PR DESCRIPTION
**Pull request by lmoureaux**
Requested by horror-vacui on Discord.

See #1517.

image

### CODE REVIEW

**Comment by psampathkumar** [comment]
Looking good.!

**Comment by jwrober** [comment]
I would have asked for a little more whitespace between values in my review `28 (+35) / 120`. It looks squished to me as is.

**Comment by lmoureaux** [comment]
Spacing as given by LaTeX:
image
Graying out the `(+35)` might help in the future.

**Comment by lmoureaux** [comment]
Typographers have put a lot of work in making LaTeX look good, that's why I'm using it as a reference here. Notice for instance how the / and + aren't the usual / and + signs.

**Comment by psampathkumar** [comment]
I think it looks good as is, especially for serif fonts, latex is usually very good reference. Not because we are writing for latex programmers, but latex was specifically designed for math/programmerish people, who are don't have to manually worry about such things. (or are bad at such things)

**Pull request merged**
