### PR TITLE
Fix performing actions from the city screen

### LINKED ISSUE #819: Disbanding units via right click in city isn't working
**Describe the bug**

@Corbeau-1 on Discord:

> Disbanding units from in-city (right-click) isn't working.

**To Reproduce**
1. See above

**Expected behavior**

Works

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: 3.0-alpha9
 - Ruleset/Longturn game (if applicable): `SIM30Test`

### PR DESCRIPTION
**Pull request by lmoureaux**
The condition in most if(can_issue_orders()) was reversed.
Closes #819.

------------

Remains to be seen if I'm the only one not getting the context menu at all. If not, I'll also add the fix to this PR.

### CODE REVIEW

**Comment by lmoureaux** [comment]
> Remains to be seen if I'm the only one not getting the context menu at all. If not, I'll also add the fix to this PR.

Added anyway.

**Comment by jwrober** [comment]
I went into a city with 3 units - Stealth Bomber, Howitzer and a AWACS. I right clicked on the Howitzer and picked set home city and then the units bar at the bottom disappeared and was replaced with the unit selection bar and I have to close the city dialog and come back in to see the units bar again.
image

**Comment by jwrober** [comment]
Same is true if I do Sentry Unit command. Activate unit does what I expect it to by closing the city dialog. If I do Disband unit, the unit bar stays there, but all the units go into a kind of greyed out state and are not clickable.

**Comment by lmoureaux** [comment]
> I went into a city with 3 units - Stealth Bomber, Howitzer and a AWACS. I right clicked on the Howitzer and picked set home city and then the units bar at the bottom disappeared and was replaced with the unit selection bar and I have to close the city dialog and come back in to see the units bar again.

Another instance of #611

**Comment by jwrober** [comment]
> Another instance of #611

Ok in that case, I can indeed disband units inside cities with a right-click.

**Review by jwrober — APPROVED** [review]

**Pull request merged**
