### PR TITLE
Implement hex_corner with MATCH_SAME

### PR DESCRIPTION
**Pull request by lmoureaux**
I need this for a hexagonal tileset project I'm doing on the side. Vectron might also benefit from this feature.

The patch touches the drawing of most terrain, all bundled tilesets seemed to work but always good to check.

### CODE REVIEW

**Review by jwrober — COMMENTED** [review]
Code seems to work fine. Docs table is a bit wonky. Wonder if we need a css change to make the page wider?

image

**Comment by lmoureaux** [comment]
> Docs table is a bit wonky.

That was already the case before, but the PR does make it wider. May need to break it down into a list. Should I do it in this PR?

**Comment by jwrober** [comment]
Oh if it was already like that, then it can stay. Might look to fix it at a later date. Maybe add an issue as a reminder.

**Comment by lmoureaux** [comment]
Rebased to allow merging

**Review by jwrober — APPROVED** [review]

**Pull request merged**
