### PR TITLE
Update backward.hpp to 1.6

### LINKED ISSUE #314: MSYS build fails in Debug, RelWithDebInfo (and Release??) modes
Linking fails due to missing Windows stack walking symbols:
```
[300/429] Linking CXX executable freeciv-qt.exe
FAILED: freeciv-qt.exe
cmd.exe /C "cd . && C:\Tools\msys64\mingw64\bin\c++.exe -O3 -DNDEBUG  client/CMakeFiles/freeciv-qt.dir/packhand.cpp.obj -o freeciv-qt.exe -Wl,--out-implib,client\libfreeciv-qt.dll.a -Wl,--major-image-version,0,--minor-image-version,0  client/libclient.a  client/gui-qt/libgui-qt.a  client/libclient.a  client/luascript/libluascript.a  client/libclient.a  client/luascript/libluascript.a  C:/Tools/msys64/mingw64/lib/libSDL2_mixer.dll.a  -lmingw32  C:/Tools/msys64/mingw64/lib/libSDL2.dll.a  client/libclient_gen.a  common/libcommon.a  common/aicore/libaicore.a  common/networking/libnetworking.a  common/scriptcore/libscriptcore.a  common/libcommon.a  common/aicore/libaicore.a  common/networking/libnetworking.a  common/scriptcore/libscriptcore.a  common/libcommon_gen.a  utility/libutility.a  C:/Tools/msys64/mingw64/lib/libQt5Network.dll.a  C:/Tools/msys64/mingw64/lib/libKF5Archive.dll.a  -lws2_32  -lwsock32  C:/Tools/msys64/mingw64/lib/libiconv.dll.a  C:/Tools/msys64/mingw64/lib/libz.dll.a  dependencies/cvercmp/libcvercmp.a  dependencies/tolua-5.2/libtolua.a  dependencies/lua-5.4/src/liblua.a  -lm  C:/Tools/msys64/mingw64/lib/libQt5Widgets.dll.a  C:/Tools/msys64/mingw64/lib/libQt5Gui.dll.a  C:/Tools/msys64/mingw64/lib/libQt5Core.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0x280): undefined reference to `__imp_SymGetModuleBase64'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0x290): undefined reference to `__imp_SymFunctionTableAccess64'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0x29c): undefined reference to `__imp_StackWalk64'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0xa84): undefined reference to `__imp_SymInitialize'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0xa8a): undefined reference to `__imp_SymGetOptions'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0xa95): undefined reference to `__imp_SymSetOptions'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0xcfc): undefined reference to `__imp_SymLoadModule64'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0xdff): undefined reference to `__imp_ImageNtHeader'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0x12c8): undefined reference to `__imp_SymFromAddr'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0x12f2): undefined reference to `__imp_UnDecorateSymbolName'
C:/Tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: utility/libutility.a(fcbacktrace.cpp.obj):fcbacktrace.cpp:(.text+0x131b): undefined reference to `__imp_SymGetLineFromAddr64'
collect2.exe: error: ld returned 1 exit status
[301/429] Generating tolua_fcdb_gen.cpp, tolua_fcdb_gen.h
ninja: build stopped: subcommand failed.
```

Confirmed in `Debug` and `RelWithDebInfo` modes. Reported in `Release` mode as well.

Could add the missing dll on the CMake side (which one?), disable stack unwinding altogether (bad for devs) or require `libunwind` (but the absence of a `pkg-config` file makes it more difficult).

### LINKED ISSUE #699: Update backward to 1.6
**Is your feature request related to a problem? Please describe.**
Upstream has released a [new version](https://github.com/bombela/backward-cpp/releases/tag/v1.6) with improved MINGW compatibility.

**Describe the solution you'd like**
Update the files.

**Describe alternatives you've considered**
None.

**Additional context**
Could help with/fix #314

### PR DESCRIPTION
**Pull request by lmoureaux**
This new upstream release adds MINGW support, which enables debug builds on Windows.
(To test: build with `-DCMAKE_BUILD_TYPE=Release`, `RelWithDebInfo`, and `Debug`.)

Closes #699.

Also adds a missing DLL.

Closes #314.

### CODE REVIEW

**Comment by jwrober** [comment]
I have libunwind installed, but I am getting this message at compile time (for all 3 options) -- Could not find any supported stack unwinding library. Is there another setting needed?

**Comment by jwrober** [comment]
I had to add a `libunwind.pc` file for pkg-config to find the package. The pacman installer does not create one.

```
# libunwind pkg-config file

prefix=/mingw64
# prefix=/mingw32
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libunwind
Description: A new implementation of a stack unwinder for C++ exceptions
Version: 13.0.0-3
Requires:
Conflicts:
Libs: -L${libdir} -lunwind
Cflags: -I${includedir}
```

I also think the `cmake/FreecivBackward.cmake` file needs an update to the message at the bottom (line 97) to be something different than the message on line 49. The second check after the unwinding library is found to look for something different should not produce the same error message.

The checks don't do a debug release, so only manual testing is finding this. Is there a second package that needs to be installed for the libdw file? I cannot seem to locate it.

Might want to consider a better finding technique if you have to add a `.pc` file.

**Comment by lmoureaux** [comment]
Lazy answer: this PR makes it *build*, which previously didn't work. I didn't even test if the traces work and are sensible.

But I agree I should've done it...

**Comment by lmoureaux** [comment]
Messages clarified, currently `libunwind` isn't supported on MINGW.

**Comment by jwrober** [comment]
> Messages clarified, currently `libunwind` isn't supported on MINGW.

That isn't entirely true. If we change the find mechanism then we can find libunwind. I used a workaround with a custom `.pc` file to help the current process to find the file. The second deal for `libdw` isn't supported on MINGW.

**Comment by lmoureaux** [comment]
> > Messages clarified, currently `libunwind` isn't supported on MINGW.
> 
> That isn't entirely true. If we change the find mechanism then we can find libunwind. I used a workaround with a custom `.pc` file to help the current process to find the file. The second deal for `libdw` isn't supported on MINGW.

It's not supported (by us) because backward-cpp doesn't support it. Even if it could be found, it wouldn't be used.

**Comment by jwrober** [comment]
Gotcha. I'll approve once the codacy issues are resolved.

**Comment by lmoureaux** [comment]
> Gotcha. I'll approve once the codacy issues are resolved.

They're not in our code anyway.

**Comment by lmoureaux** [comment]
Considering the Codacy warnings fixed since they're in 3rd-party code (and also: 3 of them are obvious false positives, the last one idk what it means but code doesn't look bad).

**Pull request merged**
