### PR TITLE
Add "Clean Nuclear Fallout" to "Unit Controls" widget

### LINKED ISSUE #2273: "Clean Fallout" activity is missing from the "Unit Controls" widget
**Describe the bug**
The "Clean Fallout" activity is missing from the "Unit Controls" widget.

**To Reproduce**
1. Move engineer on a tile with nuclear fallout.
2. See that there is no option to clean the fallout in the "Unit Controls" widget (but it is available using the "Work" menu)

**Expected behavior**
Have the option to clean fallout in the "Unit Controls" widget.

**Screenshots**
missing_fallout

**Platform and version (please complete the following information):**
 - OS: FreeBSD 14.0-RELEASE-p6
 - Freeciv21 version: 3.1-beta.1

**Additional context**
This has been noticed during [LT80](https://discord.com/channels/378908274113904641/1126193593967726722/1207598410308390943).

### PR DESCRIPTION
**Pull request by blabber**
`fallout.svg` is based on https://commons.wikimedia.org/wiki/File:Radioactive_White.svg

Closes #2273

### CODE REVIEW

**Comment by blabber** [comment]
Without this PR:
missing_fallout

With this PR:
fallout_fixed

**Comment by jwrober** [comment]
@blabber would you pls upload the save game you have w/ fallout?

**Comment by blabber** [comment]
> @blabber would you pls upload the save game you have w/ fallout?

🫴 [fallout.sav.xz.zip](https://github.com/longturn/freeciv21/files/14954576/fallout.sav.xz.zip)

**Comment by jwrober** [comment]
You need to add `fill="#000"` to the top level `<svg` open tag for it to work for both light and dark themes. On my local I did this 

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="#000" ...
```

**Comment by blabber** [comment]
> You need to add `fill="#000"` to the top level `<svg` open tag for it to work for both light and dark themes.

I changed `fallout.svg` as requested, but to be honest I still don't see any difference in light and dark theme (see screenshots below). Which irritates me even more, is that other icons (for example `mine.svg`) don't have this `fill` in their opening `<svg ...` tag.

### Screenshots
#### Light theme
light

#### Dark theme
dark

**Comment by jwrober** [comment]
Thanks for the update and submission of the icon. I am able to reproduce on my local too. I guess something is diff with how we do the unit controls bar vs other UI elements in the game that need that fill code.

**Pull request merged**
