### PR TITLE
Change build.yaml to use clang-format-18

### LINKED ISSUE #2417: Update clang-format
**Is your feature request related to a problem? Please describe.**
`clang-format-11` is no longer shipped by Ubuntu 24.04.

**Describe the solution you'd like**
Upgrade to 18.

**Describe alternatives you've considered**
* Upgrade to an intermediate version
* Upgrade to the latest version (19)

**Additional context**
The diff of 18 with respect to 11 isn't very large:
```diff
 ai/default/daimilitary.h         |  2 +-
 client/views/view_map_common.cpp |  4 ++--
 common/aicore/path_finding.cpp   |  2 +-
 common/clientutils.cpp           |  2 +-
 common/events.cpp                |  2 +-
 common/featured_text.h           |  2 +-
 common/game.h                    |  2 +-
 common/helpdata.cpp              |  2 +-
 common/map.h                     | 10 +++++-----
 common/path_finder.cpp           |  2 +-
 common/requirements.cpp          |  7 ++++---
 common/server_settings.h         |  2 +-
 server/advisors/autosettlers.cpp |  2 +-
 server/aiiface.cpp               |  2 +-
 server/diplomats.cpp             |  6 ++----
 server/savegame/savecompat.cpp   |  2 +-
 server/score.cpp                 |  2 +-
 server/techtools.cpp             |  9 +++++----
 tools/ruledit/tab_enablers.cpp   |  4 ++--
 utility/bitvector.h              |  4 ++--
 utility/log.h                    | 12 ++++++------
 utility/registry_ini.h           | 84 ++++++++++++++++++++++++++++++++++++++++++------------------------------------------
 utility/shared.h                 | 14 +++++++-------
 utility/speclist.h               | 55 +++++++++++++++++++++++++++++--------------------------
 utility/specpq.h                 |  4 ++--
 utility/specvec.h                |  2 +-
 utility/support.h                |  6 +++---
 27 files changed, 125 insertions(+), 122 deletions(-)
```
I like most of the changes.

### PR DESCRIPTION
**Pull request by jwrober**
Closes #2417

### CODE REVIEW

**Comment by lmoureaux** [comment]
Will need to reformat the code as well

**Comment by jwrober** [comment]
The instructions for the action says that the check only tests the changes in the PR. So I wasn't thinking that we needed to reformat the whole tree.

**Comment by blabber** [comment]
Commandline to bulk reformat the code (excluding dependencies). `clang-format18` is the name of the tool in FreeBSD, adapt as needed.

    find . \! -path './dependencies/*' -type f \( -name '*.hpp' -o -name '*.h' -o -name '*.cpp' -o -name '*.c' \) \
        |xargs clang-format18 -i

**Comment by jwrober** [comment]
Ok I need to revert that last commit. We have a chicken and egg problem. I need the action to update first and then update the code after its committed

**Comment by jwrober** [comment]
I'm going to start over. Closing

**Pull request closed without merging**
