### PR TITLE
❤️ Penalize buying without building

### LINKED ISSUE #310: Forbid buying a settler at size 1 then using the shields
> you can buy the setller with 30/40 shields, which is cheapier then buy, let say a caravan for 30/50 shields

This can be fixed by forcing a loss of half/all the built shields when changing production.

### PR DESCRIPTION
**Pull request by mir3x**
Fix #310 
Set 50% penalty when buying units/improvements and changing to somethign else later.

### CODE REVIEW

**Comment by lmoureaux** [comment]
Why did you remove the penalty for buildings?

**Comment by lmoureaux** [comment]
In addition, this is changing the network protocol so a netcap bump is needed.

**Comment by mir3x** [comment]
> Why did you remove the penalty for buildings?

Because some ppl might buy wonders and they would be very angry if they switch to another wonder and lose production
and I was to lazy to disticint buildings from wonders

**Comment by lmoureaux** [comment]
I see, thanks for the explanation!

**Pull request merged**
