### PR TITLE
Set MSYSTEM to MSYS32 in release.yaml

### LINKED ISSUE #1328: release.yaml fails to find cmake
**Describe the bug**
when we tag a release, `release.yaml` runs some CI action runners, one of them being to build a i686 (32bit) installer for Windows. It's failing.

**To Reproduce**
1. Tag a Release
2. Wait for the build runner to fail -- https://github.com/longturn/freeciv21/runs/8042351795?check_suite_focus=true

**Expected behavior**
Should run as expected

**Screenshots**
none

**Platform and version (please complete the following information):**
 - OS: N/A
 - Freeciv21 version: N/A
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
Two release failures in a row. Should probably hard code the full path.

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1328

### CODE REVIEW

**Review by lmoureaux — CHANGES_REQUESTED** [review]
Set `MSYSTEM` to `MINGW32` instead, as documented here: https://www.msys2.org/docs/environments/

**Comment by jwrober** [comment]
> Set `MSYSTEM` to `MINGW32` instead, as documented here: https://www.msys2.org/docs/environments/

It is already set in an `export` command and does not seem to be working 100%, so I am just hard coding the path to cmake

**Comment by lmoureaux** [comment]
> > Set `MSYSTEM` to `MINGW32` instead, as documented here: https://www.msys2.org/docs/environments/
> 
> It is already set in an `export` command and does not seem to be working 100%, so I am just hard coding the path to cmake

It's always set to `MINGW64` here:
```json
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
```

**Comment by jwrober** [comment]
I'll test another push in my fork

**Comment by jwrober** [comment]
Ok, it worked as is in my fork -- https://github.com/jwrober/freeciv21/releases/tag/3.0-beta.5

**Review by lmoureaux — APPROVED** [review]

**Pull request merged**
