### PR TITLE
Resize sidebar buttons more sensibly

### LINKED ISSUE #556: Sidebar needs to resize more sensibly.
**Describe the bug**
If you reduce the width of the sidebar the formatting is weird. 

**To Reproduce**
1) Option > Interface
2) Reduce side bar size

**Current Behavior**
Icons gets squished, fonts remain the same size and wrap badly. 

**Expected behavior**
The icons should maintain a 1:1 aspect ratio and the fonts should be automatically reduced. The user should not be expected to tweak all the other elements of the interface to get the width right. 

**Screenshots**
Current Sidebar with reduced width. 
image

**Platform and version (please complete the following information):**
 - OS: Linux (Arch)
 - Freeciv21 version: 3.0-alpha3

### PR DESCRIPTION
**Pull request by lmoureaux**
Always keep aspect ratios. Seems to work well on my small monitor.

Closes #556

I'd like two reviews on this one.

### CODE REVIEW

**Comment by lmoureaux** [comment]
This is what I get for size 2:

image

**Review by pranavtifr — COMMENTED** [review]
Should the font also be scaled correctly ? We dont expect the user to tweak around with sizes until it looks right,.

**Comment by lmoureaux** [comment]
Is it possible to make it look good with the text at such a small size?

**Comment by pranavtifr** [comment]
I think some simple constraint like.. Text shouldnt go beyond borders, and wrap it to no more than 2 lines should work (also needs to wrap sensibly along spaces).

**Comment by lmoureaux** [comment]
Then when researching "Werkzeugmaschinen" you'll get a font size smaller than one pixel…

**Comment by lmoureaux** [comment]
So I suggest that we merge this as the fundamental that makes things look better (the aspect ratio was never correct before) and handle the rest together with a much-needed iteration on the sidebar.

**Comment by pranavtifr** [comment]
Yup. Makes sense.. Hard to write warping logic when tech names can be ruleset specific.

**Comment by lmoureaux** [comment]
@jwrober's turn then?

**Comment by lmoureaux** [comment]
As per discussions on Discord, no need for another review.

**Pull request merged**
