### PR TITLE
City dialog

### PR DESCRIPTION
**Pull request by lmoureaux**
Move it to the main screen, refactor a bit, clean up NightStalker tabs.

@mir3x could you review this one?

### CODE REVIEW

**Comment by mir3x** [comment]
SEGV when starting
No idea why u create city dialog when starting client
14 0x00007ffff77bfde6 in QTabBarPrivate::init() () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff77e1525 in QTabWidgetPrivate::init() () from /usr/lib64/libQt5Widgets.so.5
#16 0x0000555555682734 in Ui_FormCityDlg::setupUi (this=0x5555565df0f0, FormCityDlg=0x5555565df0c0)
    at /home/mirex/freeciv21/build/client/gui-qt/gui-qt_autogen/include/ui_citydlg.h:135
#17 0x00005555556737e0 in city_dialog::city_dialog (this=0x5555565df0c0, parent=0x5555565e75b0) at /home/mirex/freeciv21/client/gui-qt/citydlg.cpp:1355
#18 0x000055555572407e in pageGame::pageGame (this=0x55555709f400, parent=0x55555650f4e0) at /home/mirex/freeciv21/client/gui-qt/page_game.cpp:116
#19 0x00005555556c0e3a in fc_client::fc_client (this=0x5555566f1280) at /home/mirex/freeciv21/client/gui-qt/fc_client.cpp:111

**Comment by mir3x** [comment]
With other theme works, but when trying to sell improvemtn I see some some empty Label, it might be not related

**Comment by mir3x** [comment]
Looks really nice :+1:

**Comment by mir3x** [comment]
Setting governor doesnt work

**Comment by mir3x** [comment]
I somehow escaped from city dialog and activated some unit by clicking activate then clicking improvements and map moved to some random place

**Comment by mir3x** [comment]
I started new game on experiamnetal ruleset and when closing city dialog I see unit selection with 1 unit opened and unit report F2 opened with broken size

**Comment by lmoureaux** [comment]
New version, should fix most issues.

**Comment by mir3x** [comment]
When u click next next and then close then chat/message is gone forever

**Comment by lmoureaux** [comment]
Could not find an easy fix for #3. It always uses the size of the first opened dialog. This should really be a `QListView`, then the preferred size would be correct…

**Pull request merged**
