### PR TITLE
pink entertainers

### PR DESCRIPTION
**Pull request by Canik05**
Pink entertainer specialists to make them more distinguishable from scientists.

### CODE REVIEW

**Comment by lmoureaux** [comment]
Any new artists we need to add credit for?

**Comment by Canik05** [comment]
web didn't add a new artist in specialists.spec.

still just GriffonSpade

**Comment by lmoureaux** [comment]
https://github.com/Lexxie9952/fcw.org-server/commits/master/freeciv/freeciv/data/misc/specialists.png doesn't provide any attribution either, except for Lexxie9952 as the committer.

**Comment by lmoureaux** [comment]
As we found out elsewhere, could you add `SCL` and `Lexxie` to [the `spec` file](https://github.com/longturn/freeciv21/blob/master/data/misc/specialists.spec#L10)?

**Comment by jwrober** [comment]
Looks like the .spec change is in PR #820. I think this one is ready for a squash and merge.

**Comment by lmoureaux** [comment]
Thanks @Canik05 !

**Pull request merged**
