### PR TITLE
Colorize (red) negative values on city dialog

### LINKED ISSUE #1511: Colorize/highlight the city growth if its negative
**Is your feature request related to a problem? Please describe.**
If your city is consuming more food that is needed, it will lose population when the granary is empty. The counter in the city dialog in this example says 7 turns, but that is 7 turns to a smaller city, not a larger city.

image

**Describe the solution you'd like**
Colorize (e.g. make the text red) or highlight the value for `change in` value to bring more attention to it when growth is negative. Might consider doing the same thing for the negative food at the top.

**Describe alternatives you've considered**

**Additional context**
Came up as part of evaluating PR #1494

### PR DESCRIPTION
**Pull request by jwrober**
Closes #1511

### CODE REVIEW

**Comment by jwrober** [comment]
CodeFactor found an issue with something I didn't change. Interesting.

**Review by lmoureaux — COMMENTED** [review]
> CodeFactor found an issue with something I didn't change. Interesting.

You did change the method it's pointing at :smiley:

I don't think trade, lux, or science can go negative. How much of this code could be factored out in a utility function?

**Comment by jwrober** [comment]
> I don't think trade, lux, or science can go negative. How much of this code could be factored out in a utility function?

If they don't go negative, then why "surplus"? 

IDK on the second question. Why the need for another function when in-line IF does the trick?

**Comment by lmoureaux** [comment]
> If they don't go negative, then why "surplus"?

Good question :rofl: 

> IDK on the second question. Why the need for another function when in-line IF does the trick?

To avoid repeating the same code many times (so when we update it we update it everywhere…)

Also: do we need a different color for the classic theme?

**Comment by jwrober** [comment]
> Also: do we need a different color for the classic theme?

The hard code "white" is an issue with Classic. Is there a way to unset a stylesheet?

**Comment by jwrober** [comment]
I guess I could do a bigger IF with a collection of OR in the evaluation to reduce the number of them.

**Comment by lmoureaux** [comment]
Where do we have white? I see white-space and red

**Pull request merged**
