### PR TITLE
Fix running the wasm CI

### PR DESCRIPTION
**Pull request by lmoureaux**
The CI started to fail because of an outdated cache after the latest release of
emsdk. Update the cache key to pull a fresh cache.

### CODE REVIEW

**Comment by lmoureaux** [comment]
It doesn't seem to like the latest KArchive. @zekoz is this easy for you to fix?

**Comment by jwrober** [comment]
@lmoureaux - can you rebase this to master and see what happens?

**Comment by lmoureaux** [comment]
Rebased, let's see

**Comment by lmoureaux** [comment]
```

CMake Error at emsdk/upstream/emscripten/cache/sysroot/lib/cmake/KF5Archive/KF5ArchiveTargets.cmake:56 (set_target_properties):
-- Generating done
  The link interface of target "KF5::Archive" contains:
    PkgConfig::LibZstd
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
Call Stack (most recent call first):
  emsdk/upstream/emscripten/cache/sysroot/lib/cmake/KF5Archive/KF5ArchiveConfig.cmake:55 (include)
  cmake/FreecivDependencies.cmake:121 (find_package)
  CMakeLists.txt:72 (include)
```

**Comment by jwrober** [comment]
I suggest we disable WASM CI until we can get zekoz help to determine what is going on with KF5Archive

**Comment by lmoureaux** [comment]
> I suggest we disable WASM CI until we can get zekoz help to determine what is going on with KF5Archive

Even better, we can fix it ourselves!

**Pull request merged**
