### PR TITLE
Add <releases> tag to client metainfo.xml file

### PR DESCRIPTION
**Pull request by jwrober**
No related issue. Will make future flatpak updates easier.

### CODE REVIEW

**Review by lmoureaux — CHANGES_REQUESTED** [review]
Can we generate this automatically so we don't need to remember to update it for every release?
I guess we should set it consistently in all metainfo files, not only the client one.

**Comment by lmoureaux** [comment]
Oh, and since there's a validation tool for Flatpak, it would be good to run it in the CI (can be a later project though).

**Comment by jwrober** [comment]
Note this is for `stable`. For now I think leaving it manual in stable branch is the better approach. I don't want to upset the apple cart so to speak. I want to automate it in all the files w/ CI checks in develop/master branch where we have plenty of time to work out any bugs.

**Review by lmoureaux — APPROVED** [review]
Sorry had missed the target branch!

**Pull request merged**
