### PR TITLE
Fix build issue from alpha 10

### PR DESCRIPTION
**Pull request by jwrober**
I had an explicit ref for the testing branch and removed it when initially pushed the PR for the auto tag work. Apparently it doesn't default to master branch as documented.

### CODE REVIEW

**Comment by jwrober** [comment]
ok tested it in my fork, so should work now in master branch at next release time.

**Comment by lmoureaux** [comment]
Will you fix #853 in this PR or make another one?

**Comment by jwrober** [comment]
> Will you fix #853 in this PR or make another one?

I'll go ahead and fix 853 here too. Good idea.

**Comment by jwrober** [comment]
Closes #853

**Comment by lmoureaux** [comment]
Looks good to me. @zekoz can you check if it builds without git installed?

**Comment by jwrober** [comment]
I installed a fresh VM with Kubuntu 21.10 on it and installed the base packages needed to compile fc21 without `git`, this is the configure output

```
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- AutoRevision HEAD Commit Hash: (hex) c6855 and (dec) 813141
```

So I think this patch does what we need it to.

**Comment by jwrober** [comment]
I could add some more message() to show what branch of the if() we are on.

**Review by lmoureaux — APPROVED** [review]
Proved to work. Improvements to the output can wait, this is a relatively urgent fix

**Pull request merged**
