### PR TITLE
Clear warnings when loading Dagestan and Louisiana flags

### LINKED ISSUE #2291: libpng warning: bKGD: invalid
**Describe the bug**
If you start the client from command-line, you see three of the messages in the title.

**To Reproduce**
1. Start client from command-line
2. See error

**Expected behavior**
Don't see the error
Would be good for the message to tell what image is throwing the error so we can fix it

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-beta.1
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
Found while testing PR 2288, but don't think its related.

### PR DESCRIPTION
**Pull request by lmoureaux**
libpng was complaining about "bKGD: invalid". Not sure what this means, but loading and saving with imagemagick fixed the issue.

Closes #2291.

### CODE REVIEW

**Comment by jwrober** [comment]
hm... not sure this fixes it...

```
[info] freeciv21-client (/home/jwrober/GitHub/freeciv21/client/connectdlg_common.cpp:237) - Starting freeciv21-server at /home/jwrober/GitHub/freeciv21/build_2319/freeciv21-server
[warning] freeciv21-client (unknown:0) - libpng warning: bKGD: invalid
[warning] freeciv21-client (unknown:0) - libpng warning: bKGD: invalid
```

**Comment by lmoureaux** [comment]
Which tileset are you using?

**Comment by jwrober** [comment]
I'm not even in game yet

**Comment by jwrober** [comment]
This is what is configured
image

**Comment by lmoureaux** [comment]
It probably says `Loading tileset ...` few messages up. I'll double check large tilesets

**Comment by jwrober** [comment]
My Fedora 40 workstation is running libpng 12

**Comment by jwrober** [comment]
> It probably says `Loading tileset ...` few messages up. I'll double check large tilesets

The very next line after the second "invalid" shows this message 

```
[info] freeciv21-client (/home/jwrober/GitHub/freeciv21/client/tileset/tilespec.cpp:1013) - Loading tileset "amplio2".
```

So it still seems to be before tileset selection

**Comment by lmoureaux** [comment]
Dagestan flags are now the only files causing the warnings for me (Louisiana has meanwhile been modified). I updated the PR accordingly. If you still see warnings could you apply the following patch and report the file names?

```diff
diff --git a/client/tileset/sprite.cpp b/client/tileset/sprite.cpp
index d377e19fda..14d8f549e6 100644
--- a/client/tileset/sprite.cpp
+++ b/client/tileset/sprite.cpp
@@ -29,6 +29,7 @@ QPixmap *load_gfxfile(const char *filename)
   if (QPixmapCache::find(QString(filename), entire)) {
     return entire;
   }
+  qCritical() << "Reading file" << filename;
   entire->load(QString(filename));
   QPixmapCache::insert(QString(filename), *entire);
 
```

**Review by jwrober — APPROVED** [review]
Looks great.

**Pull request merged**
