### PR TITLE
Switch to the network page when autoconnecting to an auth-enabled server

### LINKED ISSUE #540: Autoconnecting to a auth-enabled server doesn't show the password prompt
Try:
```
$ freeciv21-client -a fc21://louis94@longturn.net:5050
```
This should allow to connect to LTEx24Avi.

What actually happens is that the server asks for the password, but the client fails to recognize it. Hence it doesn't switch to `PAGE_NETWORK` and doesn't enable the password field.

Passing the password on the command line works.

### PR DESCRIPTION
**Pull request by lmoureaux**
Closes #540.

### CODE REVIEW

**Comment by jwrober** [comment]
@lmoureaux How would you suggest I test this?

**Comment by lmoureaux** [comment]
Start games, stop them, connect to other games, run LAN scans, start a game and change your mind for a scenario, oh no you wanted to load a save instead, ...

**Comment by jwrober** [comment]
Actually, I will follow the directions in PR #1304 when it is published to setup an auth enabled server and test against that.

**Review by jwrober — APPROVED** [review]
Interesting how one line can fix something. I was able to setup an auth enabled server and recreate the bug and then it went away with this patch.

**Pull request merged**
